
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `candidate_experiences` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model candidate_experiences
 * 
 */
export type candidate_experiencesModel = runtime.Types.Result.DefaultSelection<Prisma.$candidate_experiencesPayload>

export type AggregateCandidate_experiences = {
  _count: Candidate_experiencesCountAggregateOutputType | null
  _avg: Candidate_experiencesAvgAggregateOutputType | null
  _sum: Candidate_experiencesSumAggregateOutputType | null
  _min: Candidate_experiencesMinAggregateOutputType | null
  _max: Candidate_experiencesMaxAggregateOutputType | null
}

export type Candidate_experiencesAvgAggregateOutputType = {
  id: number | null
  candidate_id: number | null
}

export type Candidate_experiencesSumAggregateOutputType = {
  id: bigint | null
  candidate_id: number | null
}

export type Candidate_experiencesMinAggregateOutputType = {
  id: bigint | null
  candidate_id: number | null
  company: string | null
  designation: string | null
  start_date: string | null
  end_date: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Candidate_experiencesMaxAggregateOutputType = {
  id: bigint | null
  candidate_id: number | null
  company: string | null
  designation: string | null
  start_date: string | null
  end_date: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Candidate_experiencesCountAggregateOutputType = {
  id: number
  candidate_id: number
  company: number
  designation: number
  start_date: number
  end_date: number
  created_at: number
  updated_at: number
  _all: number
}


export type Candidate_experiencesAvgAggregateInputType = {
  id?: true
  candidate_id?: true
}

export type Candidate_experiencesSumAggregateInputType = {
  id?: true
  candidate_id?: true
}

export type Candidate_experiencesMinAggregateInputType = {
  id?: true
  candidate_id?: true
  company?: true
  designation?: true
  start_date?: true
  end_date?: true
  created_at?: true
  updated_at?: true
}

export type Candidate_experiencesMaxAggregateInputType = {
  id?: true
  candidate_id?: true
  company?: true
  designation?: true
  start_date?: true
  end_date?: true
  created_at?: true
  updated_at?: true
}

export type Candidate_experiencesCountAggregateInputType = {
  id?: true
  candidate_id?: true
  company?: true
  designation?: true
  start_date?: true
  end_date?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Candidate_experiencesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which candidate_experiences to aggregate.
   */
  where?: Prisma.candidate_experiencesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_experiences to fetch.
   */
  orderBy?: Prisma.candidate_experiencesOrderByWithRelationInput | Prisma.candidate_experiencesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.candidate_experiencesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_experiences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_experiences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned candidate_experiences
  **/
  _count?: true | Candidate_experiencesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Candidate_experiencesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Candidate_experiencesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Candidate_experiencesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Candidate_experiencesMaxAggregateInputType
}

export type GetCandidate_experiencesAggregateType<T extends Candidate_experiencesAggregateArgs> = {
      [P in keyof T & keyof AggregateCandidate_experiences]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCandidate_experiences[P]>
    : Prisma.GetScalarType<T[P], AggregateCandidate_experiences[P]>
}




export type candidate_experiencesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.candidate_experiencesWhereInput
  orderBy?: Prisma.candidate_experiencesOrderByWithAggregationInput | Prisma.candidate_experiencesOrderByWithAggregationInput[]
  by: Prisma.Candidate_experiencesScalarFieldEnum[] | Prisma.Candidate_experiencesScalarFieldEnum
  having?: Prisma.candidate_experiencesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Candidate_experiencesCountAggregateInputType | true
  _avg?: Candidate_experiencesAvgAggregateInputType
  _sum?: Candidate_experiencesSumAggregateInputType
  _min?: Candidate_experiencesMinAggregateInputType
  _max?: Candidate_experiencesMaxAggregateInputType
}

export type Candidate_experiencesGroupByOutputType = {
  id: bigint
  candidate_id: number
  company: string
  designation: string
  start_date: string
  end_date: string
  created_at: Date | null
  updated_at: Date | null
  _count: Candidate_experiencesCountAggregateOutputType | null
  _avg: Candidate_experiencesAvgAggregateOutputType | null
  _sum: Candidate_experiencesSumAggregateOutputType | null
  _min: Candidate_experiencesMinAggregateOutputType | null
  _max: Candidate_experiencesMaxAggregateOutputType | null
}

export type GetCandidate_experiencesGroupByPayload<T extends candidate_experiencesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Candidate_experiencesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Candidate_experiencesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Candidate_experiencesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Candidate_experiencesGroupByOutputType[P]>
      }
    >
  >



export type candidate_experiencesWhereInput = {
  AND?: Prisma.candidate_experiencesWhereInput | Prisma.candidate_experiencesWhereInput[]
  OR?: Prisma.candidate_experiencesWhereInput[]
  NOT?: Prisma.candidate_experiencesWhereInput | Prisma.candidate_experiencesWhereInput[]
  id?: Prisma.BigIntFilter<"candidate_experiences"> | bigint | number
  candidate_id?: Prisma.IntFilter<"candidate_experiences"> | number
  company?: Prisma.StringFilter<"candidate_experiences"> | string
  designation?: Prisma.StringFilter<"candidate_experiences"> | string
  start_date?: Prisma.StringFilter<"candidate_experiences"> | string
  end_date?: Prisma.StringFilter<"candidate_experiences"> | string
  created_at?: Prisma.DateTimeNullableFilter<"candidate_experiences"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"candidate_experiences"> | Date | string | null
}

export type candidate_experiencesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  company?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.candidate_experiencesOrderByRelevanceInput
}

export type candidate_experiencesWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.candidate_experiencesWhereInput | Prisma.candidate_experiencesWhereInput[]
  OR?: Prisma.candidate_experiencesWhereInput[]
  NOT?: Prisma.candidate_experiencesWhereInput | Prisma.candidate_experiencesWhereInput[]
  candidate_id?: Prisma.IntFilter<"candidate_experiences"> | number
  company?: Prisma.StringFilter<"candidate_experiences"> | string
  designation?: Prisma.StringFilter<"candidate_experiences"> | string
  start_date?: Prisma.StringFilter<"candidate_experiences"> | string
  end_date?: Prisma.StringFilter<"candidate_experiences"> | string
  created_at?: Prisma.DateTimeNullableFilter<"candidate_experiences"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"candidate_experiences"> | Date | string | null
}, "id">

export type candidate_experiencesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  company?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.candidate_experiencesCountOrderByAggregateInput
  _avg?: Prisma.candidate_experiencesAvgOrderByAggregateInput
  _max?: Prisma.candidate_experiencesMaxOrderByAggregateInput
  _min?: Prisma.candidate_experiencesMinOrderByAggregateInput
  _sum?: Prisma.candidate_experiencesSumOrderByAggregateInput
}

export type candidate_experiencesScalarWhereWithAggregatesInput = {
  AND?: Prisma.candidate_experiencesScalarWhereWithAggregatesInput | Prisma.candidate_experiencesScalarWhereWithAggregatesInput[]
  OR?: Prisma.candidate_experiencesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.candidate_experiencesScalarWhereWithAggregatesInput | Prisma.candidate_experiencesScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"candidate_experiences"> | bigint | number
  candidate_id?: Prisma.IntWithAggregatesFilter<"candidate_experiences"> | number
  company?: Prisma.StringWithAggregatesFilter<"candidate_experiences"> | string
  designation?: Prisma.StringWithAggregatesFilter<"candidate_experiences"> | string
  start_date?: Prisma.StringWithAggregatesFilter<"candidate_experiences"> | string
  end_date?: Prisma.StringWithAggregatesFilter<"candidate_experiences"> | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"candidate_experiences"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"candidate_experiences"> | Date | string | null
}

export type candidate_experiencesCreateInput = {
  id?: bigint | number
  candidate_id: number
  company: string
  designation: string
  start_date: string
  end_date: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type candidate_experiencesUncheckedCreateInput = {
  id?: bigint | number
  candidate_id: number
  company: string
  designation: string
  start_date: string
  end_date: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type candidate_experiencesUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  company?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_experiencesUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  company?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_experiencesCreateManyInput = {
  id?: bigint | number
  candidate_id: number
  company: string
  designation: string
  start_date: string
  end_date: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type candidate_experiencesUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  company?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_experiencesUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  company?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_experiencesOrderByRelevanceInput = {
  fields: Prisma.candidate_experiencesOrderByRelevanceFieldEnum | Prisma.candidate_experiencesOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type candidate_experiencesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  company?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type candidate_experiencesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
}

export type candidate_experiencesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  company?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type candidate_experiencesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  company?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type candidate_experiencesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
}



export type candidate_experiencesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  candidate_id?: boolean
  company?: boolean
  designation?: boolean
  start_date?: boolean
  end_date?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["candidate_experiences"]>



export type candidate_experiencesSelectScalar = {
  id?: boolean
  candidate_id?: boolean
  company?: boolean
  designation?: boolean
  start_date?: boolean
  end_date?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type candidate_experiencesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "candidate_id" | "company" | "designation" | "start_date" | "end_date" | "created_at" | "updated_at", ExtArgs["result"]["candidate_experiences"]>

export type $candidate_experiencesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "candidate_experiences"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    candidate_id: number
    company: string
    designation: string
    start_date: string
    end_date: string
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["candidate_experiences"]>
  composites: {}
}

export type candidate_experiencesGetPayload<S extends boolean | null | undefined | candidate_experiencesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$candidate_experiencesPayload, S>

export type candidate_experiencesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<candidate_experiencesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Candidate_experiencesCountAggregateInputType | true
  }

export interface candidate_experiencesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['candidate_experiences'], meta: { name: 'candidate_experiences' } }
  /**
   * Find zero or one Candidate_experiences that matches the filter.
   * @param {candidate_experiencesFindUniqueArgs} args - Arguments to find a Candidate_experiences
   * @example
   * // Get one Candidate_experiences
   * const candidate_experiences = await prisma.candidate_experiences.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends candidate_experiencesFindUniqueArgs>(args: Prisma.SelectSubset<T, candidate_experiencesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__candidate_experiencesClient<runtime.Types.Result.GetResult<Prisma.$candidate_experiencesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Candidate_experiences that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {candidate_experiencesFindUniqueOrThrowArgs} args - Arguments to find a Candidate_experiences
   * @example
   * // Get one Candidate_experiences
   * const candidate_experiences = await prisma.candidate_experiences.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends candidate_experiencesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, candidate_experiencesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__candidate_experiencesClient<runtime.Types.Result.GetResult<Prisma.$candidate_experiencesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Candidate_experiences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_experiencesFindFirstArgs} args - Arguments to find a Candidate_experiences
   * @example
   * // Get one Candidate_experiences
   * const candidate_experiences = await prisma.candidate_experiences.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends candidate_experiencesFindFirstArgs>(args?: Prisma.SelectSubset<T, candidate_experiencesFindFirstArgs<ExtArgs>>): Prisma.Prisma__candidate_experiencesClient<runtime.Types.Result.GetResult<Prisma.$candidate_experiencesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Candidate_experiences that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_experiencesFindFirstOrThrowArgs} args - Arguments to find a Candidate_experiences
   * @example
   * // Get one Candidate_experiences
   * const candidate_experiences = await prisma.candidate_experiences.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends candidate_experiencesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, candidate_experiencesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__candidate_experiencesClient<runtime.Types.Result.GetResult<Prisma.$candidate_experiencesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Candidate_experiences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_experiencesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Candidate_experiences
   * const candidate_experiences = await prisma.candidate_experiences.findMany()
   * 
   * // Get first 10 Candidate_experiences
   * const candidate_experiences = await prisma.candidate_experiences.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const candidate_experiencesWithIdOnly = await prisma.candidate_experiences.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends candidate_experiencesFindManyArgs>(args?: Prisma.SelectSubset<T, candidate_experiencesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$candidate_experiencesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Candidate_experiences.
   * @param {candidate_experiencesCreateArgs} args - Arguments to create a Candidate_experiences.
   * @example
   * // Create one Candidate_experiences
   * const Candidate_experiences = await prisma.candidate_experiences.create({
   *   data: {
   *     // ... data to create a Candidate_experiences
   *   }
   * })
   * 
   */
  create<T extends candidate_experiencesCreateArgs>(args: Prisma.SelectSubset<T, candidate_experiencesCreateArgs<ExtArgs>>): Prisma.Prisma__candidate_experiencesClient<runtime.Types.Result.GetResult<Prisma.$candidate_experiencesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Candidate_experiences.
   * @param {candidate_experiencesCreateManyArgs} args - Arguments to create many Candidate_experiences.
   * @example
   * // Create many Candidate_experiences
   * const candidate_experiences = await prisma.candidate_experiences.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends candidate_experiencesCreateManyArgs>(args?: Prisma.SelectSubset<T, candidate_experiencesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Candidate_experiences.
   * @param {candidate_experiencesDeleteArgs} args - Arguments to delete one Candidate_experiences.
   * @example
   * // Delete one Candidate_experiences
   * const Candidate_experiences = await prisma.candidate_experiences.delete({
   *   where: {
   *     // ... filter to delete one Candidate_experiences
   *   }
   * })
   * 
   */
  delete<T extends candidate_experiencesDeleteArgs>(args: Prisma.SelectSubset<T, candidate_experiencesDeleteArgs<ExtArgs>>): Prisma.Prisma__candidate_experiencesClient<runtime.Types.Result.GetResult<Prisma.$candidate_experiencesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Candidate_experiences.
   * @param {candidate_experiencesUpdateArgs} args - Arguments to update one Candidate_experiences.
   * @example
   * // Update one Candidate_experiences
   * const candidate_experiences = await prisma.candidate_experiences.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends candidate_experiencesUpdateArgs>(args: Prisma.SelectSubset<T, candidate_experiencesUpdateArgs<ExtArgs>>): Prisma.Prisma__candidate_experiencesClient<runtime.Types.Result.GetResult<Prisma.$candidate_experiencesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Candidate_experiences.
   * @param {candidate_experiencesDeleteManyArgs} args - Arguments to filter Candidate_experiences to delete.
   * @example
   * // Delete a few Candidate_experiences
   * const { count } = await prisma.candidate_experiences.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends candidate_experiencesDeleteManyArgs>(args?: Prisma.SelectSubset<T, candidate_experiencesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Candidate_experiences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_experiencesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Candidate_experiences
   * const candidate_experiences = await prisma.candidate_experiences.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends candidate_experiencesUpdateManyArgs>(args: Prisma.SelectSubset<T, candidate_experiencesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Candidate_experiences.
   * @param {candidate_experiencesUpsertArgs} args - Arguments to update or create a Candidate_experiences.
   * @example
   * // Update or create a Candidate_experiences
   * const candidate_experiences = await prisma.candidate_experiences.upsert({
   *   create: {
   *     // ... data to create a Candidate_experiences
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Candidate_experiences we want to update
   *   }
   * })
   */
  upsert<T extends candidate_experiencesUpsertArgs>(args: Prisma.SelectSubset<T, candidate_experiencesUpsertArgs<ExtArgs>>): Prisma.Prisma__candidate_experiencesClient<runtime.Types.Result.GetResult<Prisma.$candidate_experiencesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Candidate_experiences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_experiencesCountArgs} args - Arguments to filter Candidate_experiences to count.
   * @example
   * // Count the number of Candidate_experiences
   * const count = await prisma.candidate_experiences.count({
   *   where: {
   *     // ... the filter for the Candidate_experiences we want to count
   *   }
   * })
  **/
  count<T extends candidate_experiencesCountArgs>(
    args?: Prisma.Subset<T, candidate_experiencesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Candidate_experiencesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Candidate_experiences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Candidate_experiencesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Candidate_experiencesAggregateArgs>(args: Prisma.Subset<T, Candidate_experiencesAggregateArgs>): Prisma.PrismaPromise<GetCandidate_experiencesAggregateType<T>>

  /**
   * Group by Candidate_experiences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_experiencesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends candidate_experiencesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: candidate_experiencesGroupByArgs['orderBy'] }
      : { orderBy?: candidate_experiencesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, candidate_experiencesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCandidate_experiencesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the candidate_experiences model
 */
readonly fields: candidate_experiencesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for candidate_experiences.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__candidate_experiencesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the candidate_experiences model
 */
export interface candidate_experiencesFieldRefs {
  readonly id: Prisma.FieldRef<"candidate_experiences", 'BigInt'>
  readonly candidate_id: Prisma.FieldRef<"candidate_experiences", 'Int'>
  readonly company: Prisma.FieldRef<"candidate_experiences", 'String'>
  readonly designation: Prisma.FieldRef<"candidate_experiences", 'String'>
  readonly start_date: Prisma.FieldRef<"candidate_experiences", 'String'>
  readonly end_date: Prisma.FieldRef<"candidate_experiences", 'String'>
  readonly created_at: Prisma.FieldRef<"candidate_experiences", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"candidate_experiences", 'DateTime'>
}
    

// Custom InputTypes
/**
 * candidate_experiences findUnique
 */
export type candidate_experiencesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_experiences
   */
  select?: Prisma.candidate_experiencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_experiences
   */
  omit?: Prisma.candidate_experiencesOmit<ExtArgs> | null
  /**
   * Filter, which candidate_experiences to fetch.
   */
  where: Prisma.candidate_experiencesWhereUniqueInput
}

/**
 * candidate_experiences findUniqueOrThrow
 */
export type candidate_experiencesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_experiences
   */
  select?: Prisma.candidate_experiencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_experiences
   */
  omit?: Prisma.candidate_experiencesOmit<ExtArgs> | null
  /**
   * Filter, which candidate_experiences to fetch.
   */
  where: Prisma.candidate_experiencesWhereUniqueInput
}

/**
 * candidate_experiences findFirst
 */
export type candidate_experiencesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_experiences
   */
  select?: Prisma.candidate_experiencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_experiences
   */
  omit?: Prisma.candidate_experiencesOmit<ExtArgs> | null
  /**
   * Filter, which candidate_experiences to fetch.
   */
  where?: Prisma.candidate_experiencesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_experiences to fetch.
   */
  orderBy?: Prisma.candidate_experiencesOrderByWithRelationInput | Prisma.candidate_experiencesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for candidate_experiences.
   */
  cursor?: Prisma.candidate_experiencesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_experiences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_experiences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of candidate_experiences.
   */
  distinct?: Prisma.Candidate_experiencesScalarFieldEnum | Prisma.Candidate_experiencesScalarFieldEnum[]
}

/**
 * candidate_experiences findFirstOrThrow
 */
export type candidate_experiencesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_experiences
   */
  select?: Prisma.candidate_experiencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_experiences
   */
  omit?: Prisma.candidate_experiencesOmit<ExtArgs> | null
  /**
   * Filter, which candidate_experiences to fetch.
   */
  where?: Prisma.candidate_experiencesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_experiences to fetch.
   */
  orderBy?: Prisma.candidate_experiencesOrderByWithRelationInput | Prisma.candidate_experiencesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for candidate_experiences.
   */
  cursor?: Prisma.candidate_experiencesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_experiences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_experiences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of candidate_experiences.
   */
  distinct?: Prisma.Candidate_experiencesScalarFieldEnum | Prisma.Candidate_experiencesScalarFieldEnum[]
}

/**
 * candidate_experiences findMany
 */
export type candidate_experiencesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_experiences
   */
  select?: Prisma.candidate_experiencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_experiences
   */
  omit?: Prisma.candidate_experiencesOmit<ExtArgs> | null
  /**
   * Filter, which candidate_experiences to fetch.
   */
  where?: Prisma.candidate_experiencesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_experiences to fetch.
   */
  orderBy?: Prisma.candidate_experiencesOrderByWithRelationInput | Prisma.candidate_experiencesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing candidate_experiences.
   */
  cursor?: Prisma.candidate_experiencesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_experiences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_experiences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of candidate_experiences.
   */
  distinct?: Prisma.Candidate_experiencesScalarFieldEnum | Prisma.Candidate_experiencesScalarFieldEnum[]
}

/**
 * candidate_experiences create
 */
export type candidate_experiencesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_experiences
   */
  select?: Prisma.candidate_experiencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_experiences
   */
  omit?: Prisma.candidate_experiencesOmit<ExtArgs> | null
  /**
   * The data needed to create a candidate_experiences.
   */
  data: Prisma.XOR<Prisma.candidate_experiencesCreateInput, Prisma.candidate_experiencesUncheckedCreateInput>
}

/**
 * candidate_experiences createMany
 */
export type candidate_experiencesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many candidate_experiences.
   */
  data: Prisma.candidate_experiencesCreateManyInput | Prisma.candidate_experiencesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * candidate_experiences update
 */
export type candidate_experiencesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_experiences
   */
  select?: Prisma.candidate_experiencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_experiences
   */
  omit?: Prisma.candidate_experiencesOmit<ExtArgs> | null
  /**
   * The data needed to update a candidate_experiences.
   */
  data: Prisma.XOR<Prisma.candidate_experiencesUpdateInput, Prisma.candidate_experiencesUncheckedUpdateInput>
  /**
   * Choose, which candidate_experiences to update.
   */
  where: Prisma.candidate_experiencesWhereUniqueInput
}

/**
 * candidate_experiences updateMany
 */
export type candidate_experiencesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update candidate_experiences.
   */
  data: Prisma.XOR<Prisma.candidate_experiencesUpdateManyMutationInput, Prisma.candidate_experiencesUncheckedUpdateManyInput>
  /**
   * Filter which candidate_experiences to update
   */
  where?: Prisma.candidate_experiencesWhereInput
  /**
   * Limit how many candidate_experiences to update.
   */
  limit?: number
}

/**
 * candidate_experiences upsert
 */
export type candidate_experiencesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_experiences
   */
  select?: Prisma.candidate_experiencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_experiences
   */
  omit?: Prisma.candidate_experiencesOmit<ExtArgs> | null
  /**
   * The filter to search for the candidate_experiences to update in case it exists.
   */
  where: Prisma.candidate_experiencesWhereUniqueInput
  /**
   * In case the candidate_experiences found by the `where` argument doesn't exist, create a new candidate_experiences with this data.
   */
  create: Prisma.XOR<Prisma.candidate_experiencesCreateInput, Prisma.candidate_experiencesUncheckedCreateInput>
  /**
   * In case the candidate_experiences was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.candidate_experiencesUpdateInput, Prisma.candidate_experiencesUncheckedUpdateInput>
}

/**
 * candidate_experiences delete
 */
export type candidate_experiencesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_experiences
   */
  select?: Prisma.candidate_experiencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_experiences
   */
  omit?: Prisma.candidate_experiencesOmit<ExtArgs> | null
  /**
   * Filter which candidate_experiences to delete.
   */
  where: Prisma.candidate_experiencesWhereUniqueInput
}

/**
 * candidate_experiences deleteMany
 */
export type candidate_experiencesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which candidate_experiences to delete
   */
  where?: Prisma.candidate_experiencesWhereInput
  /**
   * Limit how many candidate_experiences to delete.
   */
  limit?: number
}

/**
 * candidate_experiences without action
 */
export type candidate_experiencesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_experiences
   */
  select?: Prisma.candidate_experiencesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_experiences
   */
  omit?: Prisma.candidate_experiencesOmit<ExtArgs> | null
}
