
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `candidate_resumes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model candidate_resumes
 * 
 */
export type candidate_resumesModel = runtime.Types.Result.DefaultSelection<Prisma.$candidate_resumesPayload>

export type AggregateCandidate_resumes = {
  _count: Candidate_resumesCountAggregateOutputType | null
  _avg: Candidate_resumesAvgAggregateOutputType | null
  _sum: Candidate_resumesSumAggregateOutputType | null
  _min: Candidate_resumesMinAggregateOutputType | null
  _max: Candidate_resumesMaxAggregateOutputType | null
}

export type Candidate_resumesAvgAggregateOutputType = {
  id: number | null
  candidate_id: number | null
}

export type Candidate_resumesSumAggregateOutputType = {
  id: bigint | null
  candidate_id: number | null
}

export type Candidate_resumesMinAggregateOutputType = {
  id: bigint | null
  candidate_id: number | null
  name: string | null
  file: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Candidate_resumesMaxAggregateOutputType = {
  id: bigint | null
  candidate_id: number | null
  name: string | null
  file: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Candidate_resumesCountAggregateOutputType = {
  id: number
  candidate_id: number
  name: number
  file: number
  created_at: number
  updated_at: number
  _all: number
}


export type Candidate_resumesAvgAggregateInputType = {
  id?: true
  candidate_id?: true
}

export type Candidate_resumesSumAggregateInputType = {
  id?: true
  candidate_id?: true
}

export type Candidate_resumesMinAggregateInputType = {
  id?: true
  candidate_id?: true
  name?: true
  file?: true
  created_at?: true
  updated_at?: true
}

export type Candidate_resumesMaxAggregateInputType = {
  id?: true
  candidate_id?: true
  name?: true
  file?: true
  created_at?: true
  updated_at?: true
}

export type Candidate_resumesCountAggregateInputType = {
  id?: true
  candidate_id?: true
  name?: true
  file?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Candidate_resumesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which candidate_resumes to aggregate.
   */
  where?: Prisma.candidate_resumesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_resumes to fetch.
   */
  orderBy?: Prisma.candidate_resumesOrderByWithRelationInput | Prisma.candidate_resumesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.candidate_resumesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_resumes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_resumes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned candidate_resumes
  **/
  _count?: true | Candidate_resumesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Candidate_resumesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Candidate_resumesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Candidate_resumesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Candidate_resumesMaxAggregateInputType
}

export type GetCandidate_resumesAggregateType<T extends Candidate_resumesAggregateArgs> = {
      [P in keyof T & keyof AggregateCandidate_resumes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCandidate_resumes[P]>
    : Prisma.GetScalarType<T[P], AggregateCandidate_resumes[P]>
}




export type candidate_resumesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.candidate_resumesWhereInput
  orderBy?: Prisma.candidate_resumesOrderByWithAggregationInput | Prisma.candidate_resumesOrderByWithAggregationInput[]
  by: Prisma.Candidate_resumesScalarFieldEnum[] | Prisma.Candidate_resumesScalarFieldEnum
  having?: Prisma.candidate_resumesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Candidate_resumesCountAggregateInputType | true
  _avg?: Candidate_resumesAvgAggregateInputType
  _sum?: Candidate_resumesSumAggregateInputType
  _min?: Candidate_resumesMinAggregateInputType
  _max?: Candidate_resumesMaxAggregateInputType
}

export type Candidate_resumesGroupByOutputType = {
  id: bigint
  candidate_id: number
  name: string
  file: string
  created_at: Date | null
  updated_at: Date | null
  _count: Candidate_resumesCountAggregateOutputType | null
  _avg: Candidate_resumesAvgAggregateOutputType | null
  _sum: Candidate_resumesSumAggregateOutputType | null
  _min: Candidate_resumesMinAggregateOutputType | null
  _max: Candidate_resumesMaxAggregateOutputType | null
}

export type GetCandidate_resumesGroupByPayload<T extends candidate_resumesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Candidate_resumesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Candidate_resumesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Candidate_resumesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Candidate_resumesGroupByOutputType[P]>
      }
    >
  >



export type candidate_resumesWhereInput = {
  AND?: Prisma.candidate_resumesWhereInput | Prisma.candidate_resumesWhereInput[]
  OR?: Prisma.candidate_resumesWhereInput[]
  NOT?: Prisma.candidate_resumesWhereInput | Prisma.candidate_resumesWhereInput[]
  id?: Prisma.BigIntFilter<"candidate_resumes"> | bigint | number
  candidate_id?: Prisma.IntFilter<"candidate_resumes"> | number
  name?: Prisma.StringFilter<"candidate_resumes"> | string
  file?: Prisma.StringFilter<"candidate_resumes"> | string
  created_at?: Prisma.DateTimeNullableFilter<"candidate_resumes"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"candidate_resumes"> | Date | string | null
}

export type candidate_resumesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  file?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.candidate_resumesOrderByRelevanceInput
}

export type candidate_resumesWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.candidate_resumesWhereInput | Prisma.candidate_resumesWhereInput[]
  OR?: Prisma.candidate_resumesWhereInput[]
  NOT?: Prisma.candidate_resumesWhereInput | Prisma.candidate_resumesWhereInput[]
  candidate_id?: Prisma.IntFilter<"candidate_resumes"> | number
  name?: Prisma.StringFilter<"candidate_resumes"> | string
  file?: Prisma.StringFilter<"candidate_resumes"> | string
  created_at?: Prisma.DateTimeNullableFilter<"candidate_resumes"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"candidate_resumes"> | Date | string | null
}, "id">

export type candidate_resumesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  file?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.candidate_resumesCountOrderByAggregateInput
  _avg?: Prisma.candidate_resumesAvgOrderByAggregateInput
  _max?: Prisma.candidate_resumesMaxOrderByAggregateInput
  _min?: Prisma.candidate_resumesMinOrderByAggregateInput
  _sum?: Prisma.candidate_resumesSumOrderByAggregateInput
}

export type candidate_resumesScalarWhereWithAggregatesInput = {
  AND?: Prisma.candidate_resumesScalarWhereWithAggregatesInput | Prisma.candidate_resumesScalarWhereWithAggregatesInput[]
  OR?: Prisma.candidate_resumesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.candidate_resumesScalarWhereWithAggregatesInput | Prisma.candidate_resumesScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"candidate_resumes"> | bigint | number
  candidate_id?: Prisma.IntWithAggregatesFilter<"candidate_resumes"> | number
  name?: Prisma.StringWithAggregatesFilter<"candidate_resumes"> | string
  file?: Prisma.StringWithAggregatesFilter<"candidate_resumes"> | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"candidate_resumes"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"candidate_resumes"> | Date | string | null
}

export type candidate_resumesCreateInput = {
  id?: bigint | number
  candidate_id: number
  name: string
  file: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type candidate_resumesUncheckedCreateInput = {
  id?: bigint | number
  candidate_id: number
  name: string
  file: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type candidate_resumesUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_resumesUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_resumesCreateManyInput = {
  id?: bigint | number
  candidate_id: number
  name: string
  file: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type candidate_resumesUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_resumesUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  file?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_resumesOrderByRelevanceInput = {
  fields: Prisma.candidate_resumesOrderByRelevanceFieldEnum | Prisma.candidate_resumesOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type candidate_resumesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  file?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type candidate_resumesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
}

export type candidate_resumesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  file?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type candidate_resumesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  file?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type candidate_resumesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
}



export type candidate_resumesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  candidate_id?: boolean
  name?: boolean
  file?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["candidate_resumes"]>



export type candidate_resumesSelectScalar = {
  id?: boolean
  candidate_id?: boolean
  name?: boolean
  file?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type candidate_resumesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "candidate_id" | "name" | "file" | "created_at" | "updated_at", ExtArgs["result"]["candidate_resumes"]>

export type $candidate_resumesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "candidate_resumes"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    candidate_id: number
    name: string
    file: string
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["candidate_resumes"]>
  composites: {}
}

export type candidate_resumesGetPayload<S extends boolean | null | undefined | candidate_resumesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$candidate_resumesPayload, S>

export type candidate_resumesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<candidate_resumesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Candidate_resumesCountAggregateInputType | true
  }

export interface candidate_resumesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['candidate_resumes'], meta: { name: 'candidate_resumes' } }
  /**
   * Find zero or one Candidate_resumes that matches the filter.
   * @param {candidate_resumesFindUniqueArgs} args - Arguments to find a Candidate_resumes
   * @example
   * // Get one Candidate_resumes
   * const candidate_resumes = await prisma.candidate_resumes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends candidate_resumesFindUniqueArgs>(args: Prisma.SelectSubset<T, candidate_resumesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__candidate_resumesClient<runtime.Types.Result.GetResult<Prisma.$candidate_resumesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Candidate_resumes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {candidate_resumesFindUniqueOrThrowArgs} args - Arguments to find a Candidate_resumes
   * @example
   * // Get one Candidate_resumes
   * const candidate_resumes = await prisma.candidate_resumes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends candidate_resumesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, candidate_resumesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__candidate_resumesClient<runtime.Types.Result.GetResult<Prisma.$candidate_resumesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Candidate_resumes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_resumesFindFirstArgs} args - Arguments to find a Candidate_resumes
   * @example
   * // Get one Candidate_resumes
   * const candidate_resumes = await prisma.candidate_resumes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends candidate_resumesFindFirstArgs>(args?: Prisma.SelectSubset<T, candidate_resumesFindFirstArgs<ExtArgs>>): Prisma.Prisma__candidate_resumesClient<runtime.Types.Result.GetResult<Prisma.$candidate_resumesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Candidate_resumes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_resumesFindFirstOrThrowArgs} args - Arguments to find a Candidate_resumes
   * @example
   * // Get one Candidate_resumes
   * const candidate_resumes = await prisma.candidate_resumes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends candidate_resumesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, candidate_resumesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__candidate_resumesClient<runtime.Types.Result.GetResult<Prisma.$candidate_resumesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Candidate_resumes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_resumesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Candidate_resumes
   * const candidate_resumes = await prisma.candidate_resumes.findMany()
   * 
   * // Get first 10 Candidate_resumes
   * const candidate_resumes = await prisma.candidate_resumes.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const candidate_resumesWithIdOnly = await prisma.candidate_resumes.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends candidate_resumesFindManyArgs>(args?: Prisma.SelectSubset<T, candidate_resumesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$candidate_resumesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Candidate_resumes.
   * @param {candidate_resumesCreateArgs} args - Arguments to create a Candidate_resumes.
   * @example
   * // Create one Candidate_resumes
   * const Candidate_resumes = await prisma.candidate_resumes.create({
   *   data: {
   *     // ... data to create a Candidate_resumes
   *   }
   * })
   * 
   */
  create<T extends candidate_resumesCreateArgs>(args: Prisma.SelectSubset<T, candidate_resumesCreateArgs<ExtArgs>>): Prisma.Prisma__candidate_resumesClient<runtime.Types.Result.GetResult<Prisma.$candidate_resumesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Candidate_resumes.
   * @param {candidate_resumesCreateManyArgs} args - Arguments to create many Candidate_resumes.
   * @example
   * // Create many Candidate_resumes
   * const candidate_resumes = await prisma.candidate_resumes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends candidate_resumesCreateManyArgs>(args?: Prisma.SelectSubset<T, candidate_resumesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Candidate_resumes.
   * @param {candidate_resumesDeleteArgs} args - Arguments to delete one Candidate_resumes.
   * @example
   * // Delete one Candidate_resumes
   * const Candidate_resumes = await prisma.candidate_resumes.delete({
   *   where: {
   *     // ... filter to delete one Candidate_resumes
   *   }
   * })
   * 
   */
  delete<T extends candidate_resumesDeleteArgs>(args: Prisma.SelectSubset<T, candidate_resumesDeleteArgs<ExtArgs>>): Prisma.Prisma__candidate_resumesClient<runtime.Types.Result.GetResult<Prisma.$candidate_resumesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Candidate_resumes.
   * @param {candidate_resumesUpdateArgs} args - Arguments to update one Candidate_resumes.
   * @example
   * // Update one Candidate_resumes
   * const candidate_resumes = await prisma.candidate_resumes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends candidate_resumesUpdateArgs>(args: Prisma.SelectSubset<T, candidate_resumesUpdateArgs<ExtArgs>>): Prisma.Prisma__candidate_resumesClient<runtime.Types.Result.GetResult<Prisma.$candidate_resumesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Candidate_resumes.
   * @param {candidate_resumesDeleteManyArgs} args - Arguments to filter Candidate_resumes to delete.
   * @example
   * // Delete a few Candidate_resumes
   * const { count } = await prisma.candidate_resumes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends candidate_resumesDeleteManyArgs>(args?: Prisma.SelectSubset<T, candidate_resumesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Candidate_resumes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_resumesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Candidate_resumes
   * const candidate_resumes = await prisma.candidate_resumes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends candidate_resumesUpdateManyArgs>(args: Prisma.SelectSubset<T, candidate_resumesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Candidate_resumes.
   * @param {candidate_resumesUpsertArgs} args - Arguments to update or create a Candidate_resumes.
   * @example
   * // Update or create a Candidate_resumes
   * const candidate_resumes = await prisma.candidate_resumes.upsert({
   *   create: {
   *     // ... data to create a Candidate_resumes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Candidate_resumes we want to update
   *   }
   * })
   */
  upsert<T extends candidate_resumesUpsertArgs>(args: Prisma.SelectSubset<T, candidate_resumesUpsertArgs<ExtArgs>>): Prisma.Prisma__candidate_resumesClient<runtime.Types.Result.GetResult<Prisma.$candidate_resumesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Candidate_resumes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_resumesCountArgs} args - Arguments to filter Candidate_resumes to count.
   * @example
   * // Count the number of Candidate_resumes
   * const count = await prisma.candidate_resumes.count({
   *   where: {
   *     // ... the filter for the Candidate_resumes we want to count
   *   }
   * })
  **/
  count<T extends candidate_resumesCountArgs>(
    args?: Prisma.Subset<T, candidate_resumesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Candidate_resumesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Candidate_resumes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Candidate_resumesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Candidate_resumesAggregateArgs>(args: Prisma.Subset<T, Candidate_resumesAggregateArgs>): Prisma.PrismaPromise<GetCandidate_resumesAggregateType<T>>

  /**
   * Group by Candidate_resumes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_resumesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends candidate_resumesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: candidate_resumesGroupByArgs['orderBy'] }
      : { orderBy?: candidate_resumesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, candidate_resumesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCandidate_resumesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the candidate_resumes model
 */
readonly fields: candidate_resumesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for candidate_resumes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__candidate_resumesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the candidate_resumes model
 */
export interface candidate_resumesFieldRefs {
  readonly id: Prisma.FieldRef<"candidate_resumes", 'BigInt'>
  readonly candidate_id: Prisma.FieldRef<"candidate_resumes", 'Int'>
  readonly name: Prisma.FieldRef<"candidate_resumes", 'String'>
  readonly file: Prisma.FieldRef<"candidate_resumes", 'String'>
  readonly created_at: Prisma.FieldRef<"candidate_resumes", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"candidate_resumes", 'DateTime'>
}
    

// Custom InputTypes
/**
 * candidate_resumes findUnique
 */
export type candidate_resumesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_resumes
   */
  select?: Prisma.candidate_resumesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_resumes
   */
  omit?: Prisma.candidate_resumesOmit<ExtArgs> | null
  /**
   * Filter, which candidate_resumes to fetch.
   */
  where: Prisma.candidate_resumesWhereUniqueInput
}

/**
 * candidate_resumes findUniqueOrThrow
 */
export type candidate_resumesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_resumes
   */
  select?: Prisma.candidate_resumesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_resumes
   */
  omit?: Prisma.candidate_resumesOmit<ExtArgs> | null
  /**
   * Filter, which candidate_resumes to fetch.
   */
  where: Prisma.candidate_resumesWhereUniqueInput
}

/**
 * candidate_resumes findFirst
 */
export type candidate_resumesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_resumes
   */
  select?: Prisma.candidate_resumesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_resumes
   */
  omit?: Prisma.candidate_resumesOmit<ExtArgs> | null
  /**
   * Filter, which candidate_resumes to fetch.
   */
  where?: Prisma.candidate_resumesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_resumes to fetch.
   */
  orderBy?: Prisma.candidate_resumesOrderByWithRelationInput | Prisma.candidate_resumesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for candidate_resumes.
   */
  cursor?: Prisma.candidate_resumesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_resumes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_resumes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of candidate_resumes.
   */
  distinct?: Prisma.Candidate_resumesScalarFieldEnum | Prisma.Candidate_resumesScalarFieldEnum[]
}

/**
 * candidate_resumes findFirstOrThrow
 */
export type candidate_resumesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_resumes
   */
  select?: Prisma.candidate_resumesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_resumes
   */
  omit?: Prisma.candidate_resumesOmit<ExtArgs> | null
  /**
   * Filter, which candidate_resumes to fetch.
   */
  where?: Prisma.candidate_resumesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_resumes to fetch.
   */
  orderBy?: Prisma.candidate_resumesOrderByWithRelationInput | Prisma.candidate_resumesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for candidate_resumes.
   */
  cursor?: Prisma.candidate_resumesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_resumes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_resumes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of candidate_resumes.
   */
  distinct?: Prisma.Candidate_resumesScalarFieldEnum | Prisma.Candidate_resumesScalarFieldEnum[]
}

/**
 * candidate_resumes findMany
 */
export type candidate_resumesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_resumes
   */
  select?: Prisma.candidate_resumesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_resumes
   */
  omit?: Prisma.candidate_resumesOmit<ExtArgs> | null
  /**
   * Filter, which candidate_resumes to fetch.
   */
  where?: Prisma.candidate_resumesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_resumes to fetch.
   */
  orderBy?: Prisma.candidate_resumesOrderByWithRelationInput | Prisma.candidate_resumesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing candidate_resumes.
   */
  cursor?: Prisma.candidate_resumesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_resumes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_resumes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of candidate_resumes.
   */
  distinct?: Prisma.Candidate_resumesScalarFieldEnum | Prisma.Candidate_resumesScalarFieldEnum[]
}

/**
 * candidate_resumes create
 */
export type candidate_resumesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_resumes
   */
  select?: Prisma.candidate_resumesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_resumes
   */
  omit?: Prisma.candidate_resumesOmit<ExtArgs> | null
  /**
   * The data needed to create a candidate_resumes.
   */
  data: Prisma.XOR<Prisma.candidate_resumesCreateInput, Prisma.candidate_resumesUncheckedCreateInput>
}

/**
 * candidate_resumes createMany
 */
export type candidate_resumesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many candidate_resumes.
   */
  data: Prisma.candidate_resumesCreateManyInput | Prisma.candidate_resumesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * candidate_resumes update
 */
export type candidate_resumesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_resumes
   */
  select?: Prisma.candidate_resumesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_resumes
   */
  omit?: Prisma.candidate_resumesOmit<ExtArgs> | null
  /**
   * The data needed to update a candidate_resumes.
   */
  data: Prisma.XOR<Prisma.candidate_resumesUpdateInput, Prisma.candidate_resumesUncheckedUpdateInput>
  /**
   * Choose, which candidate_resumes to update.
   */
  where: Prisma.candidate_resumesWhereUniqueInput
}

/**
 * candidate_resumes updateMany
 */
export type candidate_resumesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update candidate_resumes.
   */
  data: Prisma.XOR<Prisma.candidate_resumesUpdateManyMutationInput, Prisma.candidate_resumesUncheckedUpdateManyInput>
  /**
   * Filter which candidate_resumes to update
   */
  where?: Prisma.candidate_resumesWhereInput
  /**
   * Limit how many candidate_resumes to update.
   */
  limit?: number
}

/**
 * candidate_resumes upsert
 */
export type candidate_resumesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_resumes
   */
  select?: Prisma.candidate_resumesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_resumes
   */
  omit?: Prisma.candidate_resumesOmit<ExtArgs> | null
  /**
   * The filter to search for the candidate_resumes to update in case it exists.
   */
  where: Prisma.candidate_resumesWhereUniqueInput
  /**
   * In case the candidate_resumes found by the `where` argument doesn't exist, create a new candidate_resumes with this data.
   */
  create: Prisma.XOR<Prisma.candidate_resumesCreateInput, Prisma.candidate_resumesUncheckedCreateInput>
  /**
   * In case the candidate_resumes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.candidate_resumesUpdateInput, Prisma.candidate_resumesUncheckedUpdateInput>
}

/**
 * candidate_resumes delete
 */
export type candidate_resumesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_resumes
   */
  select?: Prisma.candidate_resumesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_resumes
   */
  omit?: Prisma.candidate_resumesOmit<ExtArgs> | null
  /**
   * Filter which candidate_resumes to delete.
   */
  where: Prisma.candidate_resumesWhereUniqueInput
}

/**
 * candidate_resumes deleteMany
 */
export type candidate_resumesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which candidate_resumes to delete
   */
  where?: Prisma.candidate_resumesWhereInput
  /**
   * Limit how many candidate_resumes to delete.
   */
  limit?: number
}

/**
 * candidate_resumes without action
 */
export type candidate_resumesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_resumes
   */
  select?: Prisma.candidate_resumesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_resumes
   */
  omit?: Prisma.candidate_resumesOmit<ExtArgs> | null
}
