
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `candidate_applications` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model candidate_applications
 * 
 */
export type candidate_applicationsModel = runtime.Types.Result.DefaultSelection<Prisma.$candidate_applicationsPayload>

export type AggregateCandidate_applications = {
  _count: Candidate_applicationsCountAggregateOutputType | null
  _avg: Candidate_applicationsAvgAggregateOutputType | null
  _sum: Candidate_applicationsSumAggregateOutputType | null
  _min: Candidate_applicationsMinAggregateOutputType | null
  _max: Candidate_applicationsMaxAggregateOutputType | null
}

export type Candidate_applicationsAvgAggregateOutputType = {
  id: number | null
  candidate_id: number | null
  job_id: number | null
}

export type Candidate_applicationsSumAggregateOutputType = {
  id: bigint | null
  candidate_id: number | null
  job_id: number | null
}

export type Candidate_applicationsMinAggregateOutputType = {
  id: bigint | null
  candidate_id: number | null
  job_id: number | null
  cover_letter: string | null
  status: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Candidate_applicationsMaxAggregateOutputType = {
  id: bigint | null
  candidate_id: number | null
  job_id: number | null
  cover_letter: string | null
  status: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Candidate_applicationsCountAggregateOutputType = {
  id: number
  candidate_id: number
  job_id: number
  cover_letter: number
  status: number
  created_at: number
  updated_at: number
  _all: number
}


export type Candidate_applicationsAvgAggregateInputType = {
  id?: true
  candidate_id?: true
  job_id?: true
}

export type Candidate_applicationsSumAggregateInputType = {
  id?: true
  candidate_id?: true
  job_id?: true
}

export type Candidate_applicationsMinAggregateInputType = {
  id?: true
  candidate_id?: true
  job_id?: true
  cover_letter?: true
  status?: true
  created_at?: true
  updated_at?: true
}

export type Candidate_applicationsMaxAggregateInputType = {
  id?: true
  candidate_id?: true
  job_id?: true
  cover_letter?: true
  status?: true
  created_at?: true
  updated_at?: true
}

export type Candidate_applicationsCountAggregateInputType = {
  id?: true
  candidate_id?: true
  job_id?: true
  cover_letter?: true
  status?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Candidate_applicationsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which candidate_applications to aggregate.
   */
  where?: Prisma.candidate_applicationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_applications to fetch.
   */
  orderBy?: Prisma.candidate_applicationsOrderByWithRelationInput | Prisma.candidate_applicationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.candidate_applicationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned candidate_applications
  **/
  _count?: true | Candidate_applicationsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Candidate_applicationsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Candidate_applicationsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Candidate_applicationsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Candidate_applicationsMaxAggregateInputType
}

export type GetCandidate_applicationsAggregateType<T extends Candidate_applicationsAggregateArgs> = {
      [P in keyof T & keyof AggregateCandidate_applications]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCandidate_applications[P]>
    : Prisma.GetScalarType<T[P], AggregateCandidate_applications[P]>
}




export type candidate_applicationsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.candidate_applicationsWhereInput
  orderBy?: Prisma.candidate_applicationsOrderByWithAggregationInput | Prisma.candidate_applicationsOrderByWithAggregationInput[]
  by: Prisma.Candidate_applicationsScalarFieldEnum[] | Prisma.Candidate_applicationsScalarFieldEnum
  having?: Prisma.candidate_applicationsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Candidate_applicationsCountAggregateInputType | true
  _avg?: Candidate_applicationsAvgAggregateInputType
  _sum?: Candidate_applicationsSumAggregateInputType
  _min?: Candidate_applicationsMinAggregateInputType
  _max?: Candidate_applicationsMaxAggregateInputType
}

export type Candidate_applicationsGroupByOutputType = {
  id: bigint
  candidate_id: number
  job_id: number
  cover_letter: string
  status: string
  created_at: Date | null
  updated_at: Date | null
  _count: Candidate_applicationsCountAggregateOutputType | null
  _avg: Candidate_applicationsAvgAggregateOutputType | null
  _sum: Candidate_applicationsSumAggregateOutputType | null
  _min: Candidate_applicationsMinAggregateOutputType | null
  _max: Candidate_applicationsMaxAggregateOutputType | null
}

export type GetCandidate_applicationsGroupByPayload<T extends candidate_applicationsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Candidate_applicationsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Candidate_applicationsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Candidate_applicationsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Candidate_applicationsGroupByOutputType[P]>
      }
    >
  >



export type candidate_applicationsWhereInput = {
  AND?: Prisma.candidate_applicationsWhereInput | Prisma.candidate_applicationsWhereInput[]
  OR?: Prisma.candidate_applicationsWhereInput[]
  NOT?: Prisma.candidate_applicationsWhereInput | Prisma.candidate_applicationsWhereInput[]
  id?: Prisma.BigIntFilter<"candidate_applications"> | bigint | number
  candidate_id?: Prisma.IntFilter<"candidate_applications"> | number
  job_id?: Prisma.IntFilter<"candidate_applications"> | number
  cover_letter?: Prisma.StringFilter<"candidate_applications"> | string
  status?: Prisma.StringFilter<"candidate_applications"> | string
  created_at?: Prisma.DateTimeNullableFilter<"candidate_applications"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"candidate_applications"> | Date | string | null
}

export type candidate_applicationsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  cover_letter?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.candidate_applicationsOrderByRelevanceInput
}

export type candidate_applicationsWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.candidate_applicationsWhereInput | Prisma.candidate_applicationsWhereInput[]
  OR?: Prisma.candidate_applicationsWhereInput[]
  NOT?: Prisma.candidate_applicationsWhereInput | Prisma.candidate_applicationsWhereInput[]
  candidate_id?: Prisma.IntFilter<"candidate_applications"> | number
  job_id?: Prisma.IntFilter<"candidate_applications"> | number
  cover_letter?: Prisma.StringFilter<"candidate_applications"> | string
  status?: Prisma.StringFilter<"candidate_applications"> | string
  created_at?: Prisma.DateTimeNullableFilter<"candidate_applications"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"candidate_applications"> | Date | string | null
}, "id">

export type candidate_applicationsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  cover_letter?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.candidate_applicationsCountOrderByAggregateInput
  _avg?: Prisma.candidate_applicationsAvgOrderByAggregateInput
  _max?: Prisma.candidate_applicationsMaxOrderByAggregateInput
  _min?: Prisma.candidate_applicationsMinOrderByAggregateInput
  _sum?: Prisma.candidate_applicationsSumOrderByAggregateInput
}

export type candidate_applicationsScalarWhereWithAggregatesInput = {
  AND?: Prisma.candidate_applicationsScalarWhereWithAggregatesInput | Prisma.candidate_applicationsScalarWhereWithAggregatesInput[]
  OR?: Prisma.candidate_applicationsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.candidate_applicationsScalarWhereWithAggregatesInput | Prisma.candidate_applicationsScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"candidate_applications"> | bigint | number
  candidate_id?: Prisma.IntWithAggregatesFilter<"candidate_applications"> | number
  job_id?: Prisma.IntWithAggregatesFilter<"candidate_applications"> | number
  cover_letter?: Prisma.StringWithAggregatesFilter<"candidate_applications"> | string
  status?: Prisma.StringWithAggregatesFilter<"candidate_applications"> | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"candidate_applications"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"candidate_applications"> | Date | string | null
}

export type candidate_applicationsCreateInput = {
  id?: bigint | number
  candidate_id: number
  job_id: number
  cover_letter: string
  status: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type candidate_applicationsUncheckedCreateInput = {
  id?: bigint | number
  candidate_id: number
  job_id: number
  cover_letter: string
  status: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type candidate_applicationsUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.IntFieldUpdateOperationsInput | number
  cover_letter?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_applicationsUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.IntFieldUpdateOperationsInput | number
  cover_letter?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_applicationsCreateManyInput = {
  id?: bigint | number
  candidate_id: number
  job_id: number
  cover_letter: string
  status: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type candidate_applicationsUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.IntFieldUpdateOperationsInput | number
  cover_letter?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_applicationsUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  candidate_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.IntFieldUpdateOperationsInput | number
  cover_letter?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type candidate_applicationsOrderByRelevanceInput = {
  fields: Prisma.candidate_applicationsOrderByRelevanceFieldEnum | Prisma.candidate_applicationsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type candidate_applicationsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  cover_letter?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type candidate_applicationsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
}

export type candidate_applicationsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  cover_letter?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type candidate_applicationsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  cover_letter?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type candidate_applicationsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  candidate_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type candidate_applicationsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  candidate_id?: boolean
  job_id?: boolean
  cover_letter?: boolean
  status?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["candidate_applications"]>



export type candidate_applicationsSelectScalar = {
  id?: boolean
  candidate_id?: boolean
  job_id?: boolean
  cover_letter?: boolean
  status?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type candidate_applicationsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "candidate_id" | "job_id" | "cover_letter" | "status" | "created_at" | "updated_at", ExtArgs["result"]["candidate_applications"]>

export type $candidate_applicationsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "candidate_applications"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    candidate_id: number
    job_id: number
    cover_letter: string
    status: string
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["candidate_applications"]>
  composites: {}
}

export type candidate_applicationsGetPayload<S extends boolean | null | undefined | candidate_applicationsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$candidate_applicationsPayload, S>

export type candidate_applicationsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<candidate_applicationsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Candidate_applicationsCountAggregateInputType | true
  }

export interface candidate_applicationsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['candidate_applications'], meta: { name: 'candidate_applications' } }
  /**
   * Find zero or one Candidate_applications that matches the filter.
   * @param {candidate_applicationsFindUniqueArgs} args - Arguments to find a Candidate_applications
   * @example
   * // Get one Candidate_applications
   * const candidate_applications = await prisma.candidate_applications.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends candidate_applicationsFindUniqueArgs>(args: Prisma.SelectSubset<T, candidate_applicationsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__candidate_applicationsClient<runtime.Types.Result.GetResult<Prisma.$candidate_applicationsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Candidate_applications that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {candidate_applicationsFindUniqueOrThrowArgs} args - Arguments to find a Candidate_applications
   * @example
   * // Get one Candidate_applications
   * const candidate_applications = await prisma.candidate_applications.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends candidate_applicationsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, candidate_applicationsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__candidate_applicationsClient<runtime.Types.Result.GetResult<Prisma.$candidate_applicationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Candidate_applications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_applicationsFindFirstArgs} args - Arguments to find a Candidate_applications
   * @example
   * // Get one Candidate_applications
   * const candidate_applications = await prisma.candidate_applications.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends candidate_applicationsFindFirstArgs>(args?: Prisma.SelectSubset<T, candidate_applicationsFindFirstArgs<ExtArgs>>): Prisma.Prisma__candidate_applicationsClient<runtime.Types.Result.GetResult<Prisma.$candidate_applicationsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Candidate_applications that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_applicationsFindFirstOrThrowArgs} args - Arguments to find a Candidate_applications
   * @example
   * // Get one Candidate_applications
   * const candidate_applications = await prisma.candidate_applications.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends candidate_applicationsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, candidate_applicationsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__candidate_applicationsClient<runtime.Types.Result.GetResult<Prisma.$candidate_applicationsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Candidate_applications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_applicationsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Candidate_applications
   * const candidate_applications = await prisma.candidate_applications.findMany()
   * 
   * // Get first 10 Candidate_applications
   * const candidate_applications = await prisma.candidate_applications.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const candidate_applicationsWithIdOnly = await prisma.candidate_applications.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends candidate_applicationsFindManyArgs>(args?: Prisma.SelectSubset<T, candidate_applicationsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$candidate_applicationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Candidate_applications.
   * @param {candidate_applicationsCreateArgs} args - Arguments to create a Candidate_applications.
   * @example
   * // Create one Candidate_applications
   * const Candidate_applications = await prisma.candidate_applications.create({
   *   data: {
   *     // ... data to create a Candidate_applications
   *   }
   * })
   * 
   */
  create<T extends candidate_applicationsCreateArgs>(args: Prisma.SelectSubset<T, candidate_applicationsCreateArgs<ExtArgs>>): Prisma.Prisma__candidate_applicationsClient<runtime.Types.Result.GetResult<Prisma.$candidate_applicationsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Candidate_applications.
   * @param {candidate_applicationsCreateManyArgs} args - Arguments to create many Candidate_applications.
   * @example
   * // Create many Candidate_applications
   * const candidate_applications = await prisma.candidate_applications.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends candidate_applicationsCreateManyArgs>(args?: Prisma.SelectSubset<T, candidate_applicationsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Candidate_applications.
   * @param {candidate_applicationsDeleteArgs} args - Arguments to delete one Candidate_applications.
   * @example
   * // Delete one Candidate_applications
   * const Candidate_applications = await prisma.candidate_applications.delete({
   *   where: {
   *     // ... filter to delete one Candidate_applications
   *   }
   * })
   * 
   */
  delete<T extends candidate_applicationsDeleteArgs>(args: Prisma.SelectSubset<T, candidate_applicationsDeleteArgs<ExtArgs>>): Prisma.Prisma__candidate_applicationsClient<runtime.Types.Result.GetResult<Prisma.$candidate_applicationsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Candidate_applications.
   * @param {candidate_applicationsUpdateArgs} args - Arguments to update one Candidate_applications.
   * @example
   * // Update one Candidate_applications
   * const candidate_applications = await prisma.candidate_applications.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends candidate_applicationsUpdateArgs>(args: Prisma.SelectSubset<T, candidate_applicationsUpdateArgs<ExtArgs>>): Prisma.Prisma__candidate_applicationsClient<runtime.Types.Result.GetResult<Prisma.$candidate_applicationsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Candidate_applications.
   * @param {candidate_applicationsDeleteManyArgs} args - Arguments to filter Candidate_applications to delete.
   * @example
   * // Delete a few Candidate_applications
   * const { count } = await prisma.candidate_applications.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends candidate_applicationsDeleteManyArgs>(args?: Prisma.SelectSubset<T, candidate_applicationsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Candidate_applications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_applicationsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Candidate_applications
   * const candidate_applications = await prisma.candidate_applications.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends candidate_applicationsUpdateManyArgs>(args: Prisma.SelectSubset<T, candidate_applicationsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Candidate_applications.
   * @param {candidate_applicationsUpsertArgs} args - Arguments to update or create a Candidate_applications.
   * @example
   * // Update or create a Candidate_applications
   * const candidate_applications = await prisma.candidate_applications.upsert({
   *   create: {
   *     // ... data to create a Candidate_applications
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Candidate_applications we want to update
   *   }
   * })
   */
  upsert<T extends candidate_applicationsUpsertArgs>(args: Prisma.SelectSubset<T, candidate_applicationsUpsertArgs<ExtArgs>>): Prisma.Prisma__candidate_applicationsClient<runtime.Types.Result.GetResult<Prisma.$candidate_applicationsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Candidate_applications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_applicationsCountArgs} args - Arguments to filter Candidate_applications to count.
   * @example
   * // Count the number of Candidate_applications
   * const count = await prisma.candidate_applications.count({
   *   where: {
   *     // ... the filter for the Candidate_applications we want to count
   *   }
   * })
  **/
  count<T extends candidate_applicationsCountArgs>(
    args?: Prisma.Subset<T, candidate_applicationsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Candidate_applicationsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Candidate_applications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Candidate_applicationsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Candidate_applicationsAggregateArgs>(args: Prisma.Subset<T, Candidate_applicationsAggregateArgs>): Prisma.PrismaPromise<GetCandidate_applicationsAggregateType<T>>

  /**
   * Group by Candidate_applications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {candidate_applicationsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends candidate_applicationsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: candidate_applicationsGroupByArgs['orderBy'] }
      : { orderBy?: candidate_applicationsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, candidate_applicationsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCandidate_applicationsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the candidate_applications model
 */
readonly fields: candidate_applicationsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for candidate_applications.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__candidate_applicationsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the candidate_applications model
 */
export interface candidate_applicationsFieldRefs {
  readonly id: Prisma.FieldRef<"candidate_applications", 'BigInt'>
  readonly candidate_id: Prisma.FieldRef<"candidate_applications", 'Int'>
  readonly job_id: Prisma.FieldRef<"candidate_applications", 'Int'>
  readonly cover_letter: Prisma.FieldRef<"candidate_applications", 'String'>
  readonly status: Prisma.FieldRef<"candidate_applications", 'String'>
  readonly created_at: Prisma.FieldRef<"candidate_applications", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"candidate_applications", 'DateTime'>
}
    

// Custom InputTypes
/**
 * candidate_applications findUnique
 */
export type candidate_applicationsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_applications
   */
  select?: Prisma.candidate_applicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_applications
   */
  omit?: Prisma.candidate_applicationsOmit<ExtArgs> | null
  /**
   * Filter, which candidate_applications to fetch.
   */
  where: Prisma.candidate_applicationsWhereUniqueInput
}

/**
 * candidate_applications findUniqueOrThrow
 */
export type candidate_applicationsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_applications
   */
  select?: Prisma.candidate_applicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_applications
   */
  omit?: Prisma.candidate_applicationsOmit<ExtArgs> | null
  /**
   * Filter, which candidate_applications to fetch.
   */
  where: Prisma.candidate_applicationsWhereUniqueInput
}

/**
 * candidate_applications findFirst
 */
export type candidate_applicationsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_applications
   */
  select?: Prisma.candidate_applicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_applications
   */
  omit?: Prisma.candidate_applicationsOmit<ExtArgs> | null
  /**
   * Filter, which candidate_applications to fetch.
   */
  where?: Prisma.candidate_applicationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_applications to fetch.
   */
  orderBy?: Prisma.candidate_applicationsOrderByWithRelationInput | Prisma.candidate_applicationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for candidate_applications.
   */
  cursor?: Prisma.candidate_applicationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of candidate_applications.
   */
  distinct?: Prisma.Candidate_applicationsScalarFieldEnum | Prisma.Candidate_applicationsScalarFieldEnum[]
}

/**
 * candidate_applications findFirstOrThrow
 */
export type candidate_applicationsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_applications
   */
  select?: Prisma.candidate_applicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_applications
   */
  omit?: Prisma.candidate_applicationsOmit<ExtArgs> | null
  /**
   * Filter, which candidate_applications to fetch.
   */
  where?: Prisma.candidate_applicationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_applications to fetch.
   */
  orderBy?: Prisma.candidate_applicationsOrderByWithRelationInput | Prisma.candidate_applicationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for candidate_applications.
   */
  cursor?: Prisma.candidate_applicationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of candidate_applications.
   */
  distinct?: Prisma.Candidate_applicationsScalarFieldEnum | Prisma.Candidate_applicationsScalarFieldEnum[]
}

/**
 * candidate_applications findMany
 */
export type candidate_applicationsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_applications
   */
  select?: Prisma.candidate_applicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_applications
   */
  omit?: Prisma.candidate_applicationsOmit<ExtArgs> | null
  /**
   * Filter, which candidate_applications to fetch.
   */
  where?: Prisma.candidate_applicationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of candidate_applications to fetch.
   */
  orderBy?: Prisma.candidate_applicationsOrderByWithRelationInput | Prisma.candidate_applicationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing candidate_applications.
   */
  cursor?: Prisma.candidate_applicationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` candidate_applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` candidate_applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of candidate_applications.
   */
  distinct?: Prisma.Candidate_applicationsScalarFieldEnum | Prisma.Candidate_applicationsScalarFieldEnum[]
}

/**
 * candidate_applications create
 */
export type candidate_applicationsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_applications
   */
  select?: Prisma.candidate_applicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_applications
   */
  omit?: Prisma.candidate_applicationsOmit<ExtArgs> | null
  /**
   * The data needed to create a candidate_applications.
   */
  data: Prisma.XOR<Prisma.candidate_applicationsCreateInput, Prisma.candidate_applicationsUncheckedCreateInput>
}

/**
 * candidate_applications createMany
 */
export type candidate_applicationsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many candidate_applications.
   */
  data: Prisma.candidate_applicationsCreateManyInput | Prisma.candidate_applicationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * candidate_applications update
 */
export type candidate_applicationsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_applications
   */
  select?: Prisma.candidate_applicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_applications
   */
  omit?: Prisma.candidate_applicationsOmit<ExtArgs> | null
  /**
   * The data needed to update a candidate_applications.
   */
  data: Prisma.XOR<Prisma.candidate_applicationsUpdateInput, Prisma.candidate_applicationsUncheckedUpdateInput>
  /**
   * Choose, which candidate_applications to update.
   */
  where: Prisma.candidate_applicationsWhereUniqueInput
}

/**
 * candidate_applications updateMany
 */
export type candidate_applicationsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update candidate_applications.
   */
  data: Prisma.XOR<Prisma.candidate_applicationsUpdateManyMutationInput, Prisma.candidate_applicationsUncheckedUpdateManyInput>
  /**
   * Filter which candidate_applications to update
   */
  where?: Prisma.candidate_applicationsWhereInput
  /**
   * Limit how many candidate_applications to update.
   */
  limit?: number
}

/**
 * candidate_applications upsert
 */
export type candidate_applicationsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_applications
   */
  select?: Prisma.candidate_applicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_applications
   */
  omit?: Prisma.candidate_applicationsOmit<ExtArgs> | null
  /**
   * The filter to search for the candidate_applications to update in case it exists.
   */
  where: Prisma.candidate_applicationsWhereUniqueInput
  /**
   * In case the candidate_applications found by the `where` argument doesn't exist, create a new candidate_applications with this data.
   */
  create: Prisma.XOR<Prisma.candidate_applicationsCreateInput, Prisma.candidate_applicationsUncheckedCreateInput>
  /**
   * In case the candidate_applications was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.candidate_applicationsUpdateInput, Prisma.candidate_applicationsUncheckedUpdateInput>
}

/**
 * candidate_applications delete
 */
export type candidate_applicationsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_applications
   */
  select?: Prisma.candidate_applicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_applications
   */
  omit?: Prisma.candidate_applicationsOmit<ExtArgs> | null
  /**
   * Filter which candidate_applications to delete.
   */
  where: Prisma.candidate_applicationsWhereUniqueInput
}

/**
 * candidate_applications deleteMany
 */
export type candidate_applicationsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which candidate_applications to delete
   */
  where?: Prisma.candidate_applicationsWhereInput
  /**
   * Limit how many candidate_applications to delete.
   */
  limit?: number
}

/**
 * candidate_applications without action
 */
export type candidate_applicationsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the candidate_applications
   */
  select?: Prisma.candidate_applicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the candidate_applications
   */
  omit?: Prisma.candidate_applicationsOmit<ExtArgs> | null
}
