
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `company_sizes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model company_sizes
 * 
 */
export type company_sizesModel = runtime.Types.Result.DefaultSelection<Prisma.$company_sizesPayload>

export type AggregateCompany_sizes = {
  _count: Company_sizesCountAggregateOutputType | null
  _avg: Company_sizesAvgAggregateOutputType | null
  _sum: Company_sizesSumAggregateOutputType | null
  _min: Company_sizesMinAggregateOutputType | null
  _max: Company_sizesMaxAggregateOutputType | null
}

export type Company_sizesAvgAggregateOutputType = {
  id: number | null
}

export type Company_sizesSumAggregateOutputType = {
  id: bigint | null
}

export type Company_sizesMinAggregateOutputType = {
  id: bigint | null
  name: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Company_sizesMaxAggregateOutputType = {
  id: bigint | null
  name: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Company_sizesCountAggregateOutputType = {
  id: number
  name: number
  created_at: number
  updated_at: number
  _all: number
}


export type Company_sizesAvgAggregateInputType = {
  id?: true
}

export type Company_sizesSumAggregateInputType = {
  id?: true
}

export type Company_sizesMinAggregateInputType = {
  id?: true
  name?: true
  created_at?: true
  updated_at?: true
}

export type Company_sizesMaxAggregateInputType = {
  id?: true
  name?: true
  created_at?: true
  updated_at?: true
}

export type Company_sizesCountAggregateInputType = {
  id?: true
  name?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Company_sizesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which company_sizes to aggregate.
   */
  where?: Prisma.company_sizesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of company_sizes to fetch.
   */
  orderBy?: Prisma.company_sizesOrderByWithRelationInput | Prisma.company_sizesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.company_sizesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` company_sizes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` company_sizes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned company_sizes
  **/
  _count?: true | Company_sizesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Company_sizesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Company_sizesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Company_sizesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Company_sizesMaxAggregateInputType
}

export type GetCompany_sizesAggregateType<T extends Company_sizesAggregateArgs> = {
      [P in keyof T & keyof AggregateCompany_sizes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCompany_sizes[P]>
    : Prisma.GetScalarType<T[P], AggregateCompany_sizes[P]>
}




export type company_sizesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.company_sizesWhereInput
  orderBy?: Prisma.company_sizesOrderByWithAggregationInput | Prisma.company_sizesOrderByWithAggregationInput[]
  by: Prisma.Company_sizesScalarFieldEnum[] | Prisma.Company_sizesScalarFieldEnum
  having?: Prisma.company_sizesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Company_sizesCountAggregateInputType | true
  _avg?: Company_sizesAvgAggregateInputType
  _sum?: Company_sizesSumAggregateInputType
  _min?: Company_sizesMinAggregateInputType
  _max?: Company_sizesMaxAggregateInputType
}

export type Company_sizesGroupByOutputType = {
  id: bigint
  name: string
  created_at: Date | null
  updated_at: Date | null
  _count: Company_sizesCountAggregateOutputType | null
  _avg: Company_sizesAvgAggregateOutputType | null
  _sum: Company_sizesSumAggregateOutputType | null
  _min: Company_sizesMinAggregateOutputType | null
  _max: Company_sizesMaxAggregateOutputType | null
}

export type GetCompany_sizesGroupByPayload<T extends company_sizesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Company_sizesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Company_sizesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Company_sizesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Company_sizesGroupByOutputType[P]>
      }
    >
  >



export type company_sizesWhereInput = {
  AND?: Prisma.company_sizesWhereInput | Prisma.company_sizesWhereInput[]
  OR?: Prisma.company_sizesWhereInput[]
  NOT?: Prisma.company_sizesWhereInput | Prisma.company_sizesWhereInput[]
  id?: Prisma.BigIntFilter<"company_sizes"> | bigint | number
  name?: Prisma.StringFilter<"company_sizes"> | string
  created_at?: Prisma.DateTimeNullableFilter<"company_sizes"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"company_sizes"> | Date | string | null
}

export type company_sizesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.company_sizesOrderByRelevanceInput
}

export type company_sizesWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.company_sizesWhereInput | Prisma.company_sizesWhereInput[]
  OR?: Prisma.company_sizesWhereInput[]
  NOT?: Prisma.company_sizesWhereInput | Prisma.company_sizesWhereInput[]
  name?: Prisma.StringFilter<"company_sizes"> | string
  created_at?: Prisma.DateTimeNullableFilter<"company_sizes"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"company_sizes"> | Date | string | null
}, "id">

export type company_sizesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.company_sizesCountOrderByAggregateInput
  _avg?: Prisma.company_sizesAvgOrderByAggregateInput
  _max?: Prisma.company_sizesMaxOrderByAggregateInput
  _min?: Prisma.company_sizesMinOrderByAggregateInput
  _sum?: Prisma.company_sizesSumOrderByAggregateInput
}

export type company_sizesScalarWhereWithAggregatesInput = {
  AND?: Prisma.company_sizesScalarWhereWithAggregatesInput | Prisma.company_sizesScalarWhereWithAggregatesInput[]
  OR?: Prisma.company_sizesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.company_sizesScalarWhereWithAggregatesInput | Prisma.company_sizesScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"company_sizes"> | bigint | number
  name?: Prisma.StringWithAggregatesFilter<"company_sizes"> | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"company_sizes"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"company_sizes"> | Date | string | null
}

export type company_sizesCreateInput = {
  id?: bigint | number
  name: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type company_sizesUncheckedCreateInput = {
  id?: bigint | number
  name: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type company_sizesUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type company_sizesUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type company_sizesCreateManyInput = {
  id?: bigint | number
  name: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type company_sizesUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type company_sizesUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type company_sizesOrderByRelevanceInput = {
  fields: Prisma.company_sizesOrderByRelevanceFieldEnum | Prisma.company_sizesOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type company_sizesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type company_sizesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type company_sizesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type company_sizesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type company_sizesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type company_sizesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["company_sizes"]>



export type company_sizesSelectScalar = {
  id?: boolean
  name?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type company_sizesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "created_at" | "updated_at", ExtArgs["result"]["company_sizes"]>

export type $company_sizesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "company_sizes"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    name: string
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["company_sizes"]>
  composites: {}
}

export type company_sizesGetPayload<S extends boolean | null | undefined | company_sizesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$company_sizesPayload, S>

export type company_sizesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<company_sizesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Company_sizesCountAggregateInputType | true
  }

export interface company_sizesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['company_sizes'], meta: { name: 'company_sizes' } }
  /**
   * Find zero or one Company_sizes that matches the filter.
   * @param {company_sizesFindUniqueArgs} args - Arguments to find a Company_sizes
   * @example
   * // Get one Company_sizes
   * const company_sizes = await prisma.company_sizes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends company_sizesFindUniqueArgs>(args: Prisma.SelectSubset<T, company_sizesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__company_sizesClient<runtime.Types.Result.GetResult<Prisma.$company_sizesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Company_sizes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {company_sizesFindUniqueOrThrowArgs} args - Arguments to find a Company_sizes
   * @example
   * // Get one Company_sizes
   * const company_sizes = await prisma.company_sizes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends company_sizesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, company_sizesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__company_sizesClient<runtime.Types.Result.GetResult<Prisma.$company_sizesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Company_sizes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {company_sizesFindFirstArgs} args - Arguments to find a Company_sizes
   * @example
   * // Get one Company_sizes
   * const company_sizes = await prisma.company_sizes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends company_sizesFindFirstArgs>(args?: Prisma.SelectSubset<T, company_sizesFindFirstArgs<ExtArgs>>): Prisma.Prisma__company_sizesClient<runtime.Types.Result.GetResult<Prisma.$company_sizesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Company_sizes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {company_sizesFindFirstOrThrowArgs} args - Arguments to find a Company_sizes
   * @example
   * // Get one Company_sizes
   * const company_sizes = await prisma.company_sizes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends company_sizesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, company_sizesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__company_sizesClient<runtime.Types.Result.GetResult<Prisma.$company_sizesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Company_sizes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {company_sizesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Company_sizes
   * const company_sizes = await prisma.company_sizes.findMany()
   * 
   * // Get first 10 Company_sizes
   * const company_sizes = await prisma.company_sizes.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const company_sizesWithIdOnly = await prisma.company_sizes.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends company_sizesFindManyArgs>(args?: Prisma.SelectSubset<T, company_sizesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$company_sizesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Company_sizes.
   * @param {company_sizesCreateArgs} args - Arguments to create a Company_sizes.
   * @example
   * // Create one Company_sizes
   * const Company_sizes = await prisma.company_sizes.create({
   *   data: {
   *     // ... data to create a Company_sizes
   *   }
   * })
   * 
   */
  create<T extends company_sizesCreateArgs>(args: Prisma.SelectSubset<T, company_sizesCreateArgs<ExtArgs>>): Prisma.Prisma__company_sizesClient<runtime.Types.Result.GetResult<Prisma.$company_sizesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Company_sizes.
   * @param {company_sizesCreateManyArgs} args - Arguments to create many Company_sizes.
   * @example
   * // Create many Company_sizes
   * const company_sizes = await prisma.company_sizes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends company_sizesCreateManyArgs>(args?: Prisma.SelectSubset<T, company_sizesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Company_sizes.
   * @param {company_sizesDeleteArgs} args - Arguments to delete one Company_sizes.
   * @example
   * // Delete one Company_sizes
   * const Company_sizes = await prisma.company_sizes.delete({
   *   where: {
   *     // ... filter to delete one Company_sizes
   *   }
   * })
   * 
   */
  delete<T extends company_sizesDeleteArgs>(args: Prisma.SelectSubset<T, company_sizesDeleteArgs<ExtArgs>>): Prisma.Prisma__company_sizesClient<runtime.Types.Result.GetResult<Prisma.$company_sizesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Company_sizes.
   * @param {company_sizesUpdateArgs} args - Arguments to update one Company_sizes.
   * @example
   * // Update one Company_sizes
   * const company_sizes = await prisma.company_sizes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends company_sizesUpdateArgs>(args: Prisma.SelectSubset<T, company_sizesUpdateArgs<ExtArgs>>): Prisma.Prisma__company_sizesClient<runtime.Types.Result.GetResult<Prisma.$company_sizesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Company_sizes.
   * @param {company_sizesDeleteManyArgs} args - Arguments to filter Company_sizes to delete.
   * @example
   * // Delete a few Company_sizes
   * const { count } = await prisma.company_sizes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends company_sizesDeleteManyArgs>(args?: Prisma.SelectSubset<T, company_sizesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Company_sizes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {company_sizesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Company_sizes
   * const company_sizes = await prisma.company_sizes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends company_sizesUpdateManyArgs>(args: Prisma.SelectSubset<T, company_sizesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Company_sizes.
   * @param {company_sizesUpsertArgs} args - Arguments to update or create a Company_sizes.
   * @example
   * // Update or create a Company_sizes
   * const company_sizes = await prisma.company_sizes.upsert({
   *   create: {
   *     // ... data to create a Company_sizes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Company_sizes we want to update
   *   }
   * })
   */
  upsert<T extends company_sizesUpsertArgs>(args: Prisma.SelectSubset<T, company_sizesUpsertArgs<ExtArgs>>): Prisma.Prisma__company_sizesClient<runtime.Types.Result.GetResult<Prisma.$company_sizesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Company_sizes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {company_sizesCountArgs} args - Arguments to filter Company_sizes to count.
   * @example
   * // Count the number of Company_sizes
   * const count = await prisma.company_sizes.count({
   *   where: {
   *     // ... the filter for the Company_sizes we want to count
   *   }
   * })
  **/
  count<T extends company_sizesCountArgs>(
    args?: Prisma.Subset<T, company_sizesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Company_sizesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Company_sizes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Company_sizesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Company_sizesAggregateArgs>(args: Prisma.Subset<T, Company_sizesAggregateArgs>): Prisma.PrismaPromise<GetCompany_sizesAggregateType<T>>

  /**
   * Group by Company_sizes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {company_sizesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends company_sizesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: company_sizesGroupByArgs['orderBy'] }
      : { orderBy?: company_sizesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, company_sizesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCompany_sizesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the company_sizes model
 */
readonly fields: company_sizesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for company_sizes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__company_sizesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the company_sizes model
 */
export interface company_sizesFieldRefs {
  readonly id: Prisma.FieldRef<"company_sizes", 'BigInt'>
  readonly name: Prisma.FieldRef<"company_sizes", 'String'>
  readonly created_at: Prisma.FieldRef<"company_sizes", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"company_sizes", 'DateTime'>
}
    

// Custom InputTypes
/**
 * company_sizes findUnique
 */
export type company_sizesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the company_sizes
   */
  select?: Prisma.company_sizesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the company_sizes
   */
  omit?: Prisma.company_sizesOmit<ExtArgs> | null
  /**
   * Filter, which company_sizes to fetch.
   */
  where: Prisma.company_sizesWhereUniqueInput
}

/**
 * company_sizes findUniqueOrThrow
 */
export type company_sizesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the company_sizes
   */
  select?: Prisma.company_sizesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the company_sizes
   */
  omit?: Prisma.company_sizesOmit<ExtArgs> | null
  /**
   * Filter, which company_sizes to fetch.
   */
  where: Prisma.company_sizesWhereUniqueInput
}

/**
 * company_sizes findFirst
 */
export type company_sizesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the company_sizes
   */
  select?: Prisma.company_sizesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the company_sizes
   */
  omit?: Prisma.company_sizesOmit<ExtArgs> | null
  /**
   * Filter, which company_sizes to fetch.
   */
  where?: Prisma.company_sizesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of company_sizes to fetch.
   */
  orderBy?: Prisma.company_sizesOrderByWithRelationInput | Prisma.company_sizesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for company_sizes.
   */
  cursor?: Prisma.company_sizesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` company_sizes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` company_sizes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of company_sizes.
   */
  distinct?: Prisma.Company_sizesScalarFieldEnum | Prisma.Company_sizesScalarFieldEnum[]
}

/**
 * company_sizes findFirstOrThrow
 */
export type company_sizesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the company_sizes
   */
  select?: Prisma.company_sizesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the company_sizes
   */
  omit?: Prisma.company_sizesOmit<ExtArgs> | null
  /**
   * Filter, which company_sizes to fetch.
   */
  where?: Prisma.company_sizesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of company_sizes to fetch.
   */
  orderBy?: Prisma.company_sizesOrderByWithRelationInput | Prisma.company_sizesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for company_sizes.
   */
  cursor?: Prisma.company_sizesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` company_sizes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` company_sizes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of company_sizes.
   */
  distinct?: Prisma.Company_sizesScalarFieldEnum | Prisma.Company_sizesScalarFieldEnum[]
}

/**
 * company_sizes findMany
 */
export type company_sizesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the company_sizes
   */
  select?: Prisma.company_sizesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the company_sizes
   */
  omit?: Prisma.company_sizesOmit<ExtArgs> | null
  /**
   * Filter, which company_sizes to fetch.
   */
  where?: Prisma.company_sizesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of company_sizes to fetch.
   */
  orderBy?: Prisma.company_sizesOrderByWithRelationInput | Prisma.company_sizesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing company_sizes.
   */
  cursor?: Prisma.company_sizesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` company_sizes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` company_sizes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of company_sizes.
   */
  distinct?: Prisma.Company_sizesScalarFieldEnum | Prisma.Company_sizesScalarFieldEnum[]
}

/**
 * company_sizes create
 */
export type company_sizesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the company_sizes
   */
  select?: Prisma.company_sizesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the company_sizes
   */
  omit?: Prisma.company_sizesOmit<ExtArgs> | null
  /**
   * The data needed to create a company_sizes.
   */
  data: Prisma.XOR<Prisma.company_sizesCreateInput, Prisma.company_sizesUncheckedCreateInput>
}

/**
 * company_sizes createMany
 */
export type company_sizesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many company_sizes.
   */
  data: Prisma.company_sizesCreateManyInput | Prisma.company_sizesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * company_sizes update
 */
export type company_sizesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the company_sizes
   */
  select?: Prisma.company_sizesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the company_sizes
   */
  omit?: Prisma.company_sizesOmit<ExtArgs> | null
  /**
   * The data needed to update a company_sizes.
   */
  data: Prisma.XOR<Prisma.company_sizesUpdateInput, Prisma.company_sizesUncheckedUpdateInput>
  /**
   * Choose, which company_sizes to update.
   */
  where: Prisma.company_sizesWhereUniqueInput
}

/**
 * company_sizes updateMany
 */
export type company_sizesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update company_sizes.
   */
  data: Prisma.XOR<Prisma.company_sizesUpdateManyMutationInput, Prisma.company_sizesUncheckedUpdateManyInput>
  /**
   * Filter which company_sizes to update
   */
  where?: Prisma.company_sizesWhereInput
  /**
   * Limit how many company_sizes to update.
   */
  limit?: number
}

/**
 * company_sizes upsert
 */
export type company_sizesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the company_sizes
   */
  select?: Prisma.company_sizesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the company_sizes
   */
  omit?: Prisma.company_sizesOmit<ExtArgs> | null
  /**
   * The filter to search for the company_sizes to update in case it exists.
   */
  where: Prisma.company_sizesWhereUniqueInput
  /**
   * In case the company_sizes found by the `where` argument doesn't exist, create a new company_sizes with this data.
   */
  create: Prisma.XOR<Prisma.company_sizesCreateInput, Prisma.company_sizesUncheckedCreateInput>
  /**
   * In case the company_sizes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.company_sizesUpdateInput, Prisma.company_sizesUncheckedUpdateInput>
}

/**
 * company_sizes delete
 */
export type company_sizesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the company_sizes
   */
  select?: Prisma.company_sizesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the company_sizes
   */
  omit?: Prisma.company_sizesOmit<ExtArgs> | null
  /**
   * Filter which company_sizes to delete.
   */
  where: Prisma.company_sizesWhereUniqueInput
}

/**
 * company_sizes deleteMany
 */
export type company_sizesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which company_sizes to delete
   */
  where?: Prisma.company_sizesWhereInput
  /**
   * Limit how many company_sizes to delete.
   */
  limit?: number
}

/**
 * company_sizes without action
 */
export type company_sizesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the company_sizes
   */
  select?: Prisma.company_sizesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the company_sizes
   */
  omit?: Prisma.company_sizesOmit<ExtArgs> | null
}
