
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `jobs` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model jobs
 * 
 */
export type jobsModel = runtime.Types.Result.DefaultSelection<Prisma.$jobsPayload>

export type AggregateJobs = {
  _count: JobsCountAggregateOutputType | null
  _avg: JobsAvgAggregateOutputType | null
  _sum: JobsSumAggregateOutputType | null
  _min: JobsMinAggregateOutputType | null
  _max: JobsMaxAggregateOutputType | null
}

export type JobsAvgAggregateOutputType = {
  id: number | null
  company_id: number | null
  vacancy: number | null
  job_category_id: number | null
  job_location_id: number | null
  job_type_id: number | null
  job_experience_id: number | null
  job_gender_id: number | null
  job_salary_range_id: number | null
  is_featured: number | null
  is_urgent: number | null
}

export type JobsSumAggregateOutputType = {
  id: bigint | null
  company_id: number | null
  vacancy: number | null
  job_category_id: number | null
  job_location_id: number | null
  job_type_id: number | null
  job_experience_id: number | null
  job_gender_id: number | null
  job_salary_range_id: number | null
  is_featured: number | null
  is_urgent: number | null
}

export type JobsMinAggregateOutputType = {
  id: bigint | null
  company_id: number | null
  title: string | null
  description: string | null
  responsibility: string | null
  skill: string | null
  education: string | null
  benefit: string | null
  deadline: string | null
  vacancy: number | null
  job_category_id: number | null
  job_location_id: number | null
  job_type_id: number | null
  job_experience_id: number | null
  job_gender_id: number | null
  job_salary_range_id: number | null
  map_code: string | null
  is_featured: number | null
  is_urgent: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type JobsMaxAggregateOutputType = {
  id: bigint | null
  company_id: number | null
  title: string | null
  description: string | null
  responsibility: string | null
  skill: string | null
  education: string | null
  benefit: string | null
  deadline: string | null
  vacancy: number | null
  job_category_id: number | null
  job_location_id: number | null
  job_type_id: number | null
  job_experience_id: number | null
  job_gender_id: number | null
  job_salary_range_id: number | null
  map_code: string | null
  is_featured: number | null
  is_urgent: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type JobsCountAggregateOutputType = {
  id: number
  company_id: number
  title: number
  description: number
  responsibility: number
  skill: number
  education: number
  benefit: number
  deadline: number
  vacancy: number
  job_category_id: number
  job_location_id: number
  job_type_id: number
  job_experience_id: number
  job_gender_id: number
  job_salary_range_id: number
  map_code: number
  is_featured: number
  is_urgent: number
  created_at: number
  updated_at: number
  _all: number
}


export type JobsAvgAggregateInputType = {
  id?: true
  company_id?: true
  vacancy?: true
  job_category_id?: true
  job_location_id?: true
  job_type_id?: true
  job_experience_id?: true
  job_gender_id?: true
  job_salary_range_id?: true
  is_featured?: true
  is_urgent?: true
}

export type JobsSumAggregateInputType = {
  id?: true
  company_id?: true
  vacancy?: true
  job_category_id?: true
  job_location_id?: true
  job_type_id?: true
  job_experience_id?: true
  job_gender_id?: true
  job_salary_range_id?: true
  is_featured?: true
  is_urgent?: true
}

export type JobsMinAggregateInputType = {
  id?: true
  company_id?: true
  title?: true
  description?: true
  responsibility?: true
  skill?: true
  education?: true
  benefit?: true
  deadline?: true
  vacancy?: true
  job_category_id?: true
  job_location_id?: true
  job_type_id?: true
  job_experience_id?: true
  job_gender_id?: true
  job_salary_range_id?: true
  map_code?: true
  is_featured?: true
  is_urgent?: true
  created_at?: true
  updated_at?: true
}

export type JobsMaxAggregateInputType = {
  id?: true
  company_id?: true
  title?: true
  description?: true
  responsibility?: true
  skill?: true
  education?: true
  benefit?: true
  deadline?: true
  vacancy?: true
  job_category_id?: true
  job_location_id?: true
  job_type_id?: true
  job_experience_id?: true
  job_gender_id?: true
  job_salary_range_id?: true
  map_code?: true
  is_featured?: true
  is_urgent?: true
  created_at?: true
  updated_at?: true
}

export type JobsCountAggregateInputType = {
  id?: true
  company_id?: true
  title?: true
  description?: true
  responsibility?: true
  skill?: true
  education?: true
  benefit?: true
  deadline?: true
  vacancy?: true
  job_category_id?: true
  job_location_id?: true
  job_type_id?: true
  job_experience_id?: true
  job_gender_id?: true
  job_salary_range_id?: true
  map_code?: true
  is_featured?: true
  is_urgent?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type JobsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which jobs to aggregate.
   */
  where?: Prisma.jobsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of jobs to fetch.
   */
  orderBy?: Prisma.jobsOrderByWithRelationInput | Prisma.jobsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.jobsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` jobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` jobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned jobs
  **/
  _count?: true | JobsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: JobsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: JobsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: JobsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: JobsMaxAggregateInputType
}

export type GetJobsAggregateType<T extends JobsAggregateArgs> = {
      [P in keyof T & keyof AggregateJobs]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateJobs[P]>
    : Prisma.GetScalarType<T[P], AggregateJobs[P]>
}




export type jobsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.jobsWhereInput
  orderBy?: Prisma.jobsOrderByWithAggregationInput | Prisma.jobsOrderByWithAggregationInput[]
  by: Prisma.JobsScalarFieldEnum[] | Prisma.JobsScalarFieldEnum
  having?: Prisma.jobsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: JobsCountAggregateInputType | true
  _avg?: JobsAvgAggregateInputType
  _sum?: JobsSumAggregateInputType
  _min?: JobsMinAggregateInputType
  _max?: JobsMaxAggregateInputType
}

export type JobsGroupByOutputType = {
  id: bigint
  company_id: number
  title: string
  description: string
  responsibility: string | null
  skill: string | null
  education: string | null
  benefit: string | null
  deadline: string
  vacancy: number
  job_category_id: number
  job_location_id: number
  job_type_id: number
  job_experience_id: number
  job_gender_id: number
  job_salary_range_id: number
  map_code: string | null
  is_featured: number
  is_urgent: number
  created_at: Date | null
  updated_at: Date | null
  _count: JobsCountAggregateOutputType | null
  _avg: JobsAvgAggregateOutputType | null
  _sum: JobsSumAggregateOutputType | null
  _min: JobsMinAggregateOutputType | null
  _max: JobsMaxAggregateOutputType | null
}

export type GetJobsGroupByPayload<T extends jobsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<JobsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof JobsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], JobsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], JobsGroupByOutputType[P]>
      }
    >
  >



export type jobsWhereInput = {
  AND?: Prisma.jobsWhereInput | Prisma.jobsWhereInput[]
  OR?: Prisma.jobsWhereInput[]
  NOT?: Prisma.jobsWhereInput | Prisma.jobsWhereInput[]
  id?: Prisma.BigIntFilter<"jobs"> | bigint | number
  company_id?: Prisma.IntFilter<"jobs"> | number
  title?: Prisma.StringFilter<"jobs"> | string
  description?: Prisma.StringFilter<"jobs"> | string
  responsibility?: Prisma.StringNullableFilter<"jobs"> | string | null
  skill?: Prisma.StringNullableFilter<"jobs"> | string | null
  education?: Prisma.StringNullableFilter<"jobs"> | string | null
  benefit?: Prisma.StringNullableFilter<"jobs"> | string | null
  deadline?: Prisma.StringFilter<"jobs"> | string
  vacancy?: Prisma.IntFilter<"jobs"> | number
  job_category_id?: Prisma.IntFilter<"jobs"> | number
  job_location_id?: Prisma.IntFilter<"jobs"> | number
  job_type_id?: Prisma.IntFilter<"jobs"> | number
  job_experience_id?: Prisma.IntFilter<"jobs"> | number
  job_gender_id?: Prisma.IntFilter<"jobs"> | number
  job_salary_range_id?: Prisma.IntFilter<"jobs"> | number
  map_code?: Prisma.StringNullableFilter<"jobs"> | string | null
  is_featured?: Prisma.IntFilter<"jobs"> | number
  is_urgent?: Prisma.IntFilter<"jobs"> | number
  created_at?: Prisma.DateTimeNullableFilter<"jobs"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"jobs"> | Date | string | null
}

export type jobsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  company_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  responsibility?: Prisma.SortOrderInput | Prisma.SortOrder
  skill?: Prisma.SortOrderInput | Prisma.SortOrder
  education?: Prisma.SortOrderInput | Prisma.SortOrder
  benefit?: Prisma.SortOrderInput | Prisma.SortOrder
  deadline?: Prisma.SortOrder
  vacancy?: Prisma.SortOrder
  job_category_id?: Prisma.SortOrder
  job_location_id?: Prisma.SortOrder
  job_type_id?: Prisma.SortOrder
  job_experience_id?: Prisma.SortOrder
  job_gender_id?: Prisma.SortOrder
  job_salary_range_id?: Prisma.SortOrder
  map_code?: Prisma.SortOrderInput | Prisma.SortOrder
  is_featured?: Prisma.SortOrder
  is_urgent?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.jobsOrderByRelevanceInput
}

export type jobsWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.jobsWhereInput | Prisma.jobsWhereInput[]
  OR?: Prisma.jobsWhereInput[]
  NOT?: Prisma.jobsWhereInput | Prisma.jobsWhereInput[]
  company_id?: Prisma.IntFilter<"jobs"> | number
  title?: Prisma.StringFilter<"jobs"> | string
  description?: Prisma.StringFilter<"jobs"> | string
  responsibility?: Prisma.StringNullableFilter<"jobs"> | string | null
  skill?: Prisma.StringNullableFilter<"jobs"> | string | null
  education?: Prisma.StringNullableFilter<"jobs"> | string | null
  benefit?: Prisma.StringNullableFilter<"jobs"> | string | null
  deadline?: Prisma.StringFilter<"jobs"> | string
  vacancy?: Prisma.IntFilter<"jobs"> | number
  job_category_id?: Prisma.IntFilter<"jobs"> | number
  job_location_id?: Prisma.IntFilter<"jobs"> | number
  job_type_id?: Prisma.IntFilter<"jobs"> | number
  job_experience_id?: Prisma.IntFilter<"jobs"> | number
  job_gender_id?: Prisma.IntFilter<"jobs"> | number
  job_salary_range_id?: Prisma.IntFilter<"jobs"> | number
  map_code?: Prisma.StringNullableFilter<"jobs"> | string | null
  is_featured?: Prisma.IntFilter<"jobs"> | number
  is_urgent?: Prisma.IntFilter<"jobs"> | number
  created_at?: Prisma.DateTimeNullableFilter<"jobs"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"jobs"> | Date | string | null
}, "id">

export type jobsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  company_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  responsibility?: Prisma.SortOrderInput | Prisma.SortOrder
  skill?: Prisma.SortOrderInput | Prisma.SortOrder
  education?: Prisma.SortOrderInput | Prisma.SortOrder
  benefit?: Prisma.SortOrderInput | Prisma.SortOrder
  deadline?: Prisma.SortOrder
  vacancy?: Prisma.SortOrder
  job_category_id?: Prisma.SortOrder
  job_location_id?: Prisma.SortOrder
  job_type_id?: Prisma.SortOrder
  job_experience_id?: Prisma.SortOrder
  job_gender_id?: Prisma.SortOrder
  job_salary_range_id?: Prisma.SortOrder
  map_code?: Prisma.SortOrderInput | Prisma.SortOrder
  is_featured?: Prisma.SortOrder
  is_urgent?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.jobsCountOrderByAggregateInput
  _avg?: Prisma.jobsAvgOrderByAggregateInput
  _max?: Prisma.jobsMaxOrderByAggregateInput
  _min?: Prisma.jobsMinOrderByAggregateInput
  _sum?: Prisma.jobsSumOrderByAggregateInput
}

export type jobsScalarWhereWithAggregatesInput = {
  AND?: Prisma.jobsScalarWhereWithAggregatesInput | Prisma.jobsScalarWhereWithAggregatesInput[]
  OR?: Prisma.jobsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.jobsScalarWhereWithAggregatesInput | Prisma.jobsScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"jobs"> | bigint | number
  company_id?: Prisma.IntWithAggregatesFilter<"jobs"> | number
  title?: Prisma.StringWithAggregatesFilter<"jobs"> | string
  description?: Prisma.StringWithAggregatesFilter<"jobs"> | string
  responsibility?: Prisma.StringNullableWithAggregatesFilter<"jobs"> | string | null
  skill?: Prisma.StringNullableWithAggregatesFilter<"jobs"> | string | null
  education?: Prisma.StringNullableWithAggregatesFilter<"jobs"> | string | null
  benefit?: Prisma.StringNullableWithAggregatesFilter<"jobs"> | string | null
  deadline?: Prisma.StringWithAggregatesFilter<"jobs"> | string
  vacancy?: Prisma.IntWithAggregatesFilter<"jobs"> | number
  job_category_id?: Prisma.IntWithAggregatesFilter<"jobs"> | number
  job_location_id?: Prisma.IntWithAggregatesFilter<"jobs"> | number
  job_type_id?: Prisma.IntWithAggregatesFilter<"jobs"> | number
  job_experience_id?: Prisma.IntWithAggregatesFilter<"jobs"> | number
  job_gender_id?: Prisma.IntWithAggregatesFilter<"jobs"> | number
  job_salary_range_id?: Prisma.IntWithAggregatesFilter<"jobs"> | number
  map_code?: Prisma.StringNullableWithAggregatesFilter<"jobs"> | string | null
  is_featured?: Prisma.IntWithAggregatesFilter<"jobs"> | number
  is_urgent?: Prisma.IntWithAggregatesFilter<"jobs"> | number
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"jobs"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"jobs"> | Date | string | null
}

export type jobsCreateInput = {
  id?: bigint | number
  company_id: number
  title: string
  description: string
  responsibility?: string | null
  skill?: string | null
  education?: string | null
  benefit?: string | null
  deadline: string
  vacancy: number
  job_category_id: number
  job_location_id: number
  job_type_id: number
  job_experience_id: number
  job_gender_id: number
  job_salary_range_id: number
  map_code?: string | null
  is_featured: number
  is_urgent: number
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type jobsUncheckedCreateInput = {
  id?: bigint | number
  company_id: number
  title: string
  description: string
  responsibility?: string | null
  skill?: string | null
  education?: string | null
  benefit?: string | null
  deadline: string
  vacancy: number
  job_category_id: number
  job_location_id: number
  job_type_id: number
  job_experience_id: number
  job_gender_id: number
  job_salary_range_id: number
  map_code?: string | null
  is_featured: number
  is_urgent: number
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type jobsUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  company_id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  responsibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skill?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deadline?: Prisma.StringFieldUpdateOperationsInput | string
  vacancy?: Prisma.IntFieldUpdateOperationsInput | number
  job_category_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_location_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_type_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_experience_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_gender_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_salary_range_id?: Prisma.IntFieldUpdateOperationsInput | number
  map_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_featured?: Prisma.IntFieldUpdateOperationsInput | number
  is_urgent?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type jobsUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  company_id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  responsibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skill?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deadline?: Prisma.StringFieldUpdateOperationsInput | string
  vacancy?: Prisma.IntFieldUpdateOperationsInput | number
  job_category_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_location_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_type_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_experience_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_gender_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_salary_range_id?: Prisma.IntFieldUpdateOperationsInput | number
  map_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_featured?: Prisma.IntFieldUpdateOperationsInput | number
  is_urgent?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type jobsCreateManyInput = {
  id?: bigint | number
  company_id: number
  title: string
  description: string
  responsibility?: string | null
  skill?: string | null
  education?: string | null
  benefit?: string | null
  deadline: string
  vacancy: number
  job_category_id: number
  job_location_id: number
  job_type_id: number
  job_experience_id: number
  job_gender_id: number
  job_salary_range_id: number
  map_code?: string | null
  is_featured: number
  is_urgent: number
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type jobsUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  company_id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  responsibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skill?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deadline?: Prisma.StringFieldUpdateOperationsInput | string
  vacancy?: Prisma.IntFieldUpdateOperationsInput | number
  job_category_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_location_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_type_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_experience_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_gender_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_salary_range_id?: Prisma.IntFieldUpdateOperationsInput | number
  map_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_featured?: Prisma.IntFieldUpdateOperationsInput | number
  is_urgent?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type jobsUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  company_id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  responsibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skill?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  education?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  benefit?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deadline?: Prisma.StringFieldUpdateOperationsInput | string
  vacancy?: Prisma.IntFieldUpdateOperationsInput | number
  job_category_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_location_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_type_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_experience_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_gender_id?: Prisma.IntFieldUpdateOperationsInput | number
  job_salary_range_id?: Prisma.IntFieldUpdateOperationsInput | number
  map_code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_featured?: Prisma.IntFieldUpdateOperationsInput | number
  is_urgent?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type jobsOrderByRelevanceInput = {
  fields: Prisma.jobsOrderByRelevanceFieldEnum | Prisma.jobsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type jobsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  company_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  responsibility?: Prisma.SortOrder
  skill?: Prisma.SortOrder
  education?: Prisma.SortOrder
  benefit?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  vacancy?: Prisma.SortOrder
  job_category_id?: Prisma.SortOrder
  job_location_id?: Prisma.SortOrder
  job_type_id?: Prisma.SortOrder
  job_experience_id?: Prisma.SortOrder
  job_gender_id?: Prisma.SortOrder
  job_salary_range_id?: Prisma.SortOrder
  map_code?: Prisma.SortOrder
  is_featured?: Prisma.SortOrder
  is_urgent?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type jobsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  company_id?: Prisma.SortOrder
  vacancy?: Prisma.SortOrder
  job_category_id?: Prisma.SortOrder
  job_location_id?: Prisma.SortOrder
  job_type_id?: Prisma.SortOrder
  job_experience_id?: Prisma.SortOrder
  job_gender_id?: Prisma.SortOrder
  job_salary_range_id?: Prisma.SortOrder
  is_featured?: Prisma.SortOrder
  is_urgent?: Prisma.SortOrder
}

export type jobsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  company_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  responsibility?: Prisma.SortOrder
  skill?: Prisma.SortOrder
  education?: Prisma.SortOrder
  benefit?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  vacancy?: Prisma.SortOrder
  job_category_id?: Prisma.SortOrder
  job_location_id?: Prisma.SortOrder
  job_type_id?: Prisma.SortOrder
  job_experience_id?: Prisma.SortOrder
  job_gender_id?: Prisma.SortOrder
  job_salary_range_id?: Prisma.SortOrder
  map_code?: Prisma.SortOrder
  is_featured?: Prisma.SortOrder
  is_urgent?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type jobsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  company_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  responsibility?: Prisma.SortOrder
  skill?: Prisma.SortOrder
  education?: Prisma.SortOrder
  benefit?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  vacancy?: Prisma.SortOrder
  job_category_id?: Prisma.SortOrder
  job_location_id?: Prisma.SortOrder
  job_type_id?: Prisma.SortOrder
  job_experience_id?: Prisma.SortOrder
  job_gender_id?: Prisma.SortOrder
  job_salary_range_id?: Prisma.SortOrder
  map_code?: Prisma.SortOrder
  is_featured?: Prisma.SortOrder
  is_urgent?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type jobsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  company_id?: Prisma.SortOrder
  vacancy?: Prisma.SortOrder
  job_category_id?: Prisma.SortOrder
  job_location_id?: Prisma.SortOrder
  job_type_id?: Prisma.SortOrder
  job_experience_id?: Prisma.SortOrder
  job_gender_id?: Prisma.SortOrder
  job_salary_range_id?: Prisma.SortOrder
  is_featured?: Prisma.SortOrder
  is_urgent?: Prisma.SortOrder
}



export type jobsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  company_id?: boolean
  title?: boolean
  description?: boolean
  responsibility?: boolean
  skill?: boolean
  education?: boolean
  benefit?: boolean
  deadline?: boolean
  vacancy?: boolean
  job_category_id?: boolean
  job_location_id?: boolean
  job_type_id?: boolean
  job_experience_id?: boolean
  job_gender_id?: boolean
  job_salary_range_id?: boolean
  map_code?: boolean
  is_featured?: boolean
  is_urgent?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["jobs"]>



export type jobsSelectScalar = {
  id?: boolean
  company_id?: boolean
  title?: boolean
  description?: boolean
  responsibility?: boolean
  skill?: boolean
  education?: boolean
  benefit?: boolean
  deadline?: boolean
  vacancy?: boolean
  job_category_id?: boolean
  job_location_id?: boolean
  job_type_id?: boolean
  job_experience_id?: boolean
  job_gender_id?: boolean
  job_salary_range_id?: boolean
  map_code?: boolean
  is_featured?: boolean
  is_urgent?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type jobsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "company_id" | "title" | "description" | "responsibility" | "skill" | "education" | "benefit" | "deadline" | "vacancy" | "job_category_id" | "job_location_id" | "job_type_id" | "job_experience_id" | "job_gender_id" | "job_salary_range_id" | "map_code" | "is_featured" | "is_urgent" | "created_at" | "updated_at", ExtArgs["result"]["jobs"]>

export type $jobsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "jobs"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    company_id: number
    title: string
    description: string
    responsibility: string | null
    skill: string | null
    education: string | null
    benefit: string | null
    deadline: string
    vacancy: number
    job_category_id: number
    job_location_id: number
    job_type_id: number
    job_experience_id: number
    job_gender_id: number
    job_salary_range_id: number
    map_code: string | null
    is_featured: number
    is_urgent: number
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["jobs"]>
  composites: {}
}

export type jobsGetPayload<S extends boolean | null | undefined | jobsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$jobsPayload, S>

export type jobsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<jobsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: JobsCountAggregateInputType | true
  }

export interface jobsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['jobs'], meta: { name: 'jobs' } }
  /**
   * Find zero or one Jobs that matches the filter.
   * @param {jobsFindUniqueArgs} args - Arguments to find a Jobs
   * @example
   * // Get one Jobs
   * const jobs = await prisma.jobs.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends jobsFindUniqueArgs>(args: Prisma.SelectSubset<T, jobsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__jobsClient<runtime.Types.Result.GetResult<Prisma.$jobsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Jobs that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {jobsFindUniqueOrThrowArgs} args - Arguments to find a Jobs
   * @example
   * // Get one Jobs
   * const jobs = await prisma.jobs.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends jobsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, jobsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__jobsClient<runtime.Types.Result.GetResult<Prisma.$jobsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Jobs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {jobsFindFirstArgs} args - Arguments to find a Jobs
   * @example
   * // Get one Jobs
   * const jobs = await prisma.jobs.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends jobsFindFirstArgs>(args?: Prisma.SelectSubset<T, jobsFindFirstArgs<ExtArgs>>): Prisma.Prisma__jobsClient<runtime.Types.Result.GetResult<Prisma.$jobsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Jobs that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {jobsFindFirstOrThrowArgs} args - Arguments to find a Jobs
   * @example
   * // Get one Jobs
   * const jobs = await prisma.jobs.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends jobsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, jobsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__jobsClient<runtime.Types.Result.GetResult<Prisma.$jobsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Jobs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {jobsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Jobs
   * const jobs = await prisma.jobs.findMany()
   * 
   * // Get first 10 Jobs
   * const jobs = await prisma.jobs.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const jobsWithIdOnly = await prisma.jobs.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends jobsFindManyArgs>(args?: Prisma.SelectSubset<T, jobsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$jobsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Jobs.
   * @param {jobsCreateArgs} args - Arguments to create a Jobs.
   * @example
   * // Create one Jobs
   * const Jobs = await prisma.jobs.create({
   *   data: {
   *     // ... data to create a Jobs
   *   }
   * })
   * 
   */
  create<T extends jobsCreateArgs>(args: Prisma.SelectSubset<T, jobsCreateArgs<ExtArgs>>): Prisma.Prisma__jobsClient<runtime.Types.Result.GetResult<Prisma.$jobsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Jobs.
   * @param {jobsCreateManyArgs} args - Arguments to create many Jobs.
   * @example
   * // Create many Jobs
   * const jobs = await prisma.jobs.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends jobsCreateManyArgs>(args?: Prisma.SelectSubset<T, jobsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Jobs.
   * @param {jobsDeleteArgs} args - Arguments to delete one Jobs.
   * @example
   * // Delete one Jobs
   * const Jobs = await prisma.jobs.delete({
   *   where: {
   *     // ... filter to delete one Jobs
   *   }
   * })
   * 
   */
  delete<T extends jobsDeleteArgs>(args: Prisma.SelectSubset<T, jobsDeleteArgs<ExtArgs>>): Prisma.Prisma__jobsClient<runtime.Types.Result.GetResult<Prisma.$jobsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Jobs.
   * @param {jobsUpdateArgs} args - Arguments to update one Jobs.
   * @example
   * // Update one Jobs
   * const jobs = await prisma.jobs.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends jobsUpdateArgs>(args: Prisma.SelectSubset<T, jobsUpdateArgs<ExtArgs>>): Prisma.Prisma__jobsClient<runtime.Types.Result.GetResult<Prisma.$jobsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Jobs.
   * @param {jobsDeleteManyArgs} args - Arguments to filter Jobs to delete.
   * @example
   * // Delete a few Jobs
   * const { count } = await prisma.jobs.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends jobsDeleteManyArgs>(args?: Prisma.SelectSubset<T, jobsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Jobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {jobsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Jobs
   * const jobs = await prisma.jobs.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends jobsUpdateManyArgs>(args: Prisma.SelectSubset<T, jobsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Jobs.
   * @param {jobsUpsertArgs} args - Arguments to update or create a Jobs.
   * @example
   * // Update or create a Jobs
   * const jobs = await prisma.jobs.upsert({
   *   create: {
   *     // ... data to create a Jobs
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Jobs we want to update
   *   }
   * })
   */
  upsert<T extends jobsUpsertArgs>(args: Prisma.SelectSubset<T, jobsUpsertArgs<ExtArgs>>): Prisma.Prisma__jobsClient<runtime.Types.Result.GetResult<Prisma.$jobsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Jobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {jobsCountArgs} args - Arguments to filter Jobs to count.
   * @example
   * // Count the number of Jobs
   * const count = await prisma.jobs.count({
   *   where: {
   *     // ... the filter for the Jobs we want to count
   *   }
   * })
  **/
  count<T extends jobsCountArgs>(
    args?: Prisma.Subset<T, jobsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], JobsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Jobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends JobsAggregateArgs>(args: Prisma.Subset<T, JobsAggregateArgs>): Prisma.PrismaPromise<GetJobsAggregateType<T>>

  /**
   * Group by Jobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {jobsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends jobsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: jobsGroupByArgs['orderBy'] }
      : { orderBy?: jobsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, jobsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetJobsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the jobs model
 */
readonly fields: jobsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for jobs.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__jobsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the jobs model
 */
export interface jobsFieldRefs {
  readonly id: Prisma.FieldRef<"jobs", 'BigInt'>
  readonly company_id: Prisma.FieldRef<"jobs", 'Int'>
  readonly title: Prisma.FieldRef<"jobs", 'String'>
  readonly description: Prisma.FieldRef<"jobs", 'String'>
  readonly responsibility: Prisma.FieldRef<"jobs", 'String'>
  readonly skill: Prisma.FieldRef<"jobs", 'String'>
  readonly education: Prisma.FieldRef<"jobs", 'String'>
  readonly benefit: Prisma.FieldRef<"jobs", 'String'>
  readonly deadline: Prisma.FieldRef<"jobs", 'String'>
  readonly vacancy: Prisma.FieldRef<"jobs", 'Int'>
  readonly job_category_id: Prisma.FieldRef<"jobs", 'Int'>
  readonly job_location_id: Prisma.FieldRef<"jobs", 'Int'>
  readonly job_type_id: Prisma.FieldRef<"jobs", 'Int'>
  readonly job_experience_id: Prisma.FieldRef<"jobs", 'Int'>
  readonly job_gender_id: Prisma.FieldRef<"jobs", 'Int'>
  readonly job_salary_range_id: Prisma.FieldRef<"jobs", 'Int'>
  readonly map_code: Prisma.FieldRef<"jobs", 'String'>
  readonly is_featured: Prisma.FieldRef<"jobs", 'Int'>
  readonly is_urgent: Prisma.FieldRef<"jobs", 'Int'>
  readonly created_at: Prisma.FieldRef<"jobs", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"jobs", 'DateTime'>
}
    

// Custom InputTypes
/**
 * jobs findUnique
 */
export type jobsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the jobs
   */
  select?: Prisma.jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the jobs
   */
  omit?: Prisma.jobsOmit<ExtArgs> | null
  /**
   * Filter, which jobs to fetch.
   */
  where: Prisma.jobsWhereUniqueInput
}

/**
 * jobs findUniqueOrThrow
 */
export type jobsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the jobs
   */
  select?: Prisma.jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the jobs
   */
  omit?: Prisma.jobsOmit<ExtArgs> | null
  /**
   * Filter, which jobs to fetch.
   */
  where: Prisma.jobsWhereUniqueInput
}

/**
 * jobs findFirst
 */
export type jobsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the jobs
   */
  select?: Prisma.jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the jobs
   */
  omit?: Prisma.jobsOmit<ExtArgs> | null
  /**
   * Filter, which jobs to fetch.
   */
  where?: Prisma.jobsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of jobs to fetch.
   */
  orderBy?: Prisma.jobsOrderByWithRelationInput | Prisma.jobsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for jobs.
   */
  cursor?: Prisma.jobsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` jobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` jobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of jobs.
   */
  distinct?: Prisma.JobsScalarFieldEnum | Prisma.JobsScalarFieldEnum[]
}

/**
 * jobs findFirstOrThrow
 */
export type jobsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the jobs
   */
  select?: Prisma.jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the jobs
   */
  omit?: Prisma.jobsOmit<ExtArgs> | null
  /**
   * Filter, which jobs to fetch.
   */
  where?: Prisma.jobsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of jobs to fetch.
   */
  orderBy?: Prisma.jobsOrderByWithRelationInput | Prisma.jobsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for jobs.
   */
  cursor?: Prisma.jobsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` jobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` jobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of jobs.
   */
  distinct?: Prisma.JobsScalarFieldEnum | Prisma.JobsScalarFieldEnum[]
}

/**
 * jobs findMany
 */
export type jobsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the jobs
   */
  select?: Prisma.jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the jobs
   */
  omit?: Prisma.jobsOmit<ExtArgs> | null
  /**
   * Filter, which jobs to fetch.
   */
  where?: Prisma.jobsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of jobs to fetch.
   */
  orderBy?: Prisma.jobsOrderByWithRelationInput | Prisma.jobsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing jobs.
   */
  cursor?: Prisma.jobsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` jobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` jobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of jobs.
   */
  distinct?: Prisma.JobsScalarFieldEnum | Prisma.JobsScalarFieldEnum[]
}

/**
 * jobs create
 */
export type jobsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the jobs
   */
  select?: Prisma.jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the jobs
   */
  omit?: Prisma.jobsOmit<ExtArgs> | null
  /**
   * The data needed to create a jobs.
   */
  data: Prisma.XOR<Prisma.jobsCreateInput, Prisma.jobsUncheckedCreateInput>
}

/**
 * jobs createMany
 */
export type jobsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many jobs.
   */
  data: Prisma.jobsCreateManyInput | Prisma.jobsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * jobs update
 */
export type jobsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the jobs
   */
  select?: Prisma.jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the jobs
   */
  omit?: Prisma.jobsOmit<ExtArgs> | null
  /**
   * The data needed to update a jobs.
   */
  data: Prisma.XOR<Prisma.jobsUpdateInput, Prisma.jobsUncheckedUpdateInput>
  /**
   * Choose, which jobs to update.
   */
  where: Prisma.jobsWhereUniqueInput
}

/**
 * jobs updateMany
 */
export type jobsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update jobs.
   */
  data: Prisma.XOR<Prisma.jobsUpdateManyMutationInput, Prisma.jobsUncheckedUpdateManyInput>
  /**
   * Filter which jobs to update
   */
  where?: Prisma.jobsWhereInput
  /**
   * Limit how many jobs to update.
   */
  limit?: number
}

/**
 * jobs upsert
 */
export type jobsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the jobs
   */
  select?: Prisma.jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the jobs
   */
  omit?: Prisma.jobsOmit<ExtArgs> | null
  /**
   * The filter to search for the jobs to update in case it exists.
   */
  where: Prisma.jobsWhereUniqueInput
  /**
   * In case the jobs found by the `where` argument doesn't exist, create a new jobs with this data.
   */
  create: Prisma.XOR<Prisma.jobsCreateInput, Prisma.jobsUncheckedCreateInput>
  /**
   * In case the jobs was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.jobsUpdateInput, Prisma.jobsUncheckedUpdateInput>
}

/**
 * jobs delete
 */
export type jobsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the jobs
   */
  select?: Prisma.jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the jobs
   */
  omit?: Prisma.jobsOmit<ExtArgs> | null
  /**
   * Filter which jobs to delete.
   */
  where: Prisma.jobsWhereUniqueInput
}

/**
 * jobs deleteMany
 */
export type jobsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which jobs to delete
   */
  where?: Prisma.jobsWhereInput
  /**
   * Limit how many jobs to delete.
   */
  limit?: number
}

/**
 * jobs without action
 */
export type jobsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the jobs
   */
  select?: Prisma.jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the jobs
   */
  omit?: Prisma.jobsOmit<ExtArgs> | null
}
