
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `page_other_items` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model page_other_items
 * 
 */
export type page_other_itemsModel = runtime.Types.Result.DefaultSelection<Prisma.$page_other_itemsPayload>

export type AggregatePage_other_items = {
  _count: Page_other_itemsCountAggregateOutputType | null
  _avg: Page_other_itemsAvgAggregateOutputType | null
  _sum: Page_other_itemsSumAggregateOutputType | null
  _min: Page_other_itemsMinAggregateOutputType | null
  _max: Page_other_itemsMaxAggregateOutputType | null
}

export type Page_other_itemsAvgAggregateOutputType = {
  id: number | null
}

export type Page_other_itemsSumAggregateOutputType = {
  id: bigint | null
}

export type Page_other_itemsMinAggregateOutputType = {
  id: bigint | null
  login_page_heading: string | null
  login_page_title: string | null
  login_page_meta_description: string | null
  signup_page_heading: string | null
  signup_page_title: string | null
  signup_page_meta_description: string | null
  forget_password_page_heading: string | null
  forget_password_page_title: string | null
  forget_password_page_meta_description: string | null
  job_listing_page_heading: string | null
  job_listing_page_title: string | null
  job_listing_page_meta_description: string | null
  company_listing_page_heading: string | null
  company_listing_page_title: string | null
  company_listing_page_meta_description: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Page_other_itemsMaxAggregateOutputType = {
  id: bigint | null
  login_page_heading: string | null
  login_page_title: string | null
  login_page_meta_description: string | null
  signup_page_heading: string | null
  signup_page_title: string | null
  signup_page_meta_description: string | null
  forget_password_page_heading: string | null
  forget_password_page_title: string | null
  forget_password_page_meta_description: string | null
  job_listing_page_heading: string | null
  job_listing_page_title: string | null
  job_listing_page_meta_description: string | null
  company_listing_page_heading: string | null
  company_listing_page_title: string | null
  company_listing_page_meta_description: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Page_other_itemsCountAggregateOutputType = {
  id: number
  login_page_heading: number
  login_page_title: number
  login_page_meta_description: number
  signup_page_heading: number
  signup_page_title: number
  signup_page_meta_description: number
  forget_password_page_heading: number
  forget_password_page_title: number
  forget_password_page_meta_description: number
  job_listing_page_heading: number
  job_listing_page_title: number
  job_listing_page_meta_description: number
  company_listing_page_heading: number
  company_listing_page_title: number
  company_listing_page_meta_description: number
  created_at: number
  updated_at: number
  _all: number
}


export type Page_other_itemsAvgAggregateInputType = {
  id?: true
}

export type Page_other_itemsSumAggregateInputType = {
  id?: true
}

export type Page_other_itemsMinAggregateInputType = {
  id?: true
  login_page_heading?: true
  login_page_title?: true
  login_page_meta_description?: true
  signup_page_heading?: true
  signup_page_title?: true
  signup_page_meta_description?: true
  forget_password_page_heading?: true
  forget_password_page_title?: true
  forget_password_page_meta_description?: true
  job_listing_page_heading?: true
  job_listing_page_title?: true
  job_listing_page_meta_description?: true
  company_listing_page_heading?: true
  company_listing_page_title?: true
  company_listing_page_meta_description?: true
  created_at?: true
  updated_at?: true
}

export type Page_other_itemsMaxAggregateInputType = {
  id?: true
  login_page_heading?: true
  login_page_title?: true
  login_page_meta_description?: true
  signup_page_heading?: true
  signup_page_title?: true
  signup_page_meta_description?: true
  forget_password_page_heading?: true
  forget_password_page_title?: true
  forget_password_page_meta_description?: true
  job_listing_page_heading?: true
  job_listing_page_title?: true
  job_listing_page_meta_description?: true
  company_listing_page_heading?: true
  company_listing_page_title?: true
  company_listing_page_meta_description?: true
  created_at?: true
  updated_at?: true
}

export type Page_other_itemsCountAggregateInputType = {
  id?: true
  login_page_heading?: true
  login_page_title?: true
  login_page_meta_description?: true
  signup_page_heading?: true
  signup_page_title?: true
  signup_page_meta_description?: true
  forget_password_page_heading?: true
  forget_password_page_title?: true
  forget_password_page_meta_description?: true
  job_listing_page_heading?: true
  job_listing_page_title?: true
  job_listing_page_meta_description?: true
  company_listing_page_heading?: true
  company_listing_page_title?: true
  company_listing_page_meta_description?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Page_other_itemsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which page_other_items to aggregate.
   */
  where?: Prisma.page_other_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of page_other_items to fetch.
   */
  orderBy?: Prisma.page_other_itemsOrderByWithRelationInput | Prisma.page_other_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.page_other_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` page_other_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` page_other_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned page_other_items
  **/
  _count?: true | Page_other_itemsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Page_other_itemsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Page_other_itemsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Page_other_itemsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Page_other_itemsMaxAggregateInputType
}

export type GetPage_other_itemsAggregateType<T extends Page_other_itemsAggregateArgs> = {
      [P in keyof T & keyof AggregatePage_other_items]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePage_other_items[P]>
    : Prisma.GetScalarType<T[P], AggregatePage_other_items[P]>
}




export type page_other_itemsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.page_other_itemsWhereInput
  orderBy?: Prisma.page_other_itemsOrderByWithAggregationInput | Prisma.page_other_itemsOrderByWithAggregationInput[]
  by: Prisma.Page_other_itemsScalarFieldEnum[] | Prisma.Page_other_itemsScalarFieldEnum
  having?: Prisma.page_other_itemsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Page_other_itemsCountAggregateInputType | true
  _avg?: Page_other_itemsAvgAggregateInputType
  _sum?: Page_other_itemsSumAggregateInputType
  _min?: Page_other_itemsMinAggregateInputType
  _max?: Page_other_itemsMaxAggregateInputType
}

export type Page_other_itemsGroupByOutputType = {
  id: bigint
  login_page_heading: string
  login_page_title: string | null
  login_page_meta_description: string | null
  signup_page_heading: string
  signup_page_title: string | null
  signup_page_meta_description: string | null
  forget_password_page_heading: string
  forget_password_page_title: string | null
  forget_password_page_meta_description: string | null
  job_listing_page_heading: string
  job_listing_page_title: string | null
  job_listing_page_meta_description: string | null
  company_listing_page_heading: string
  company_listing_page_title: string | null
  company_listing_page_meta_description: string | null
  created_at: Date | null
  updated_at: Date | null
  _count: Page_other_itemsCountAggregateOutputType | null
  _avg: Page_other_itemsAvgAggregateOutputType | null
  _sum: Page_other_itemsSumAggregateOutputType | null
  _min: Page_other_itemsMinAggregateOutputType | null
  _max: Page_other_itemsMaxAggregateOutputType | null
}

export type GetPage_other_itemsGroupByPayload<T extends page_other_itemsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Page_other_itemsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Page_other_itemsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Page_other_itemsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Page_other_itemsGroupByOutputType[P]>
      }
    >
  >



export type page_other_itemsWhereInput = {
  AND?: Prisma.page_other_itemsWhereInput | Prisma.page_other_itemsWhereInput[]
  OR?: Prisma.page_other_itemsWhereInput[]
  NOT?: Prisma.page_other_itemsWhereInput | Prisma.page_other_itemsWhereInput[]
  id?: Prisma.BigIntFilter<"page_other_items"> | bigint | number
  login_page_heading?: Prisma.StringFilter<"page_other_items"> | string
  login_page_title?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  login_page_meta_description?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  signup_page_heading?: Prisma.StringFilter<"page_other_items"> | string
  signup_page_title?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  signup_page_meta_description?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  forget_password_page_heading?: Prisma.StringFilter<"page_other_items"> | string
  forget_password_page_title?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  forget_password_page_meta_description?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  job_listing_page_heading?: Prisma.StringFilter<"page_other_items"> | string
  job_listing_page_title?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  job_listing_page_meta_description?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  company_listing_page_heading?: Prisma.StringFilter<"page_other_items"> | string
  company_listing_page_title?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  company_listing_page_meta_description?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"page_other_items"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"page_other_items"> | Date | string | null
}

export type page_other_itemsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  login_page_heading?: Prisma.SortOrder
  login_page_title?: Prisma.SortOrderInput | Prisma.SortOrder
  login_page_meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  signup_page_heading?: Prisma.SortOrder
  signup_page_title?: Prisma.SortOrderInput | Prisma.SortOrder
  signup_page_meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  forget_password_page_heading?: Prisma.SortOrder
  forget_password_page_title?: Prisma.SortOrderInput | Prisma.SortOrder
  forget_password_page_meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  job_listing_page_heading?: Prisma.SortOrder
  job_listing_page_title?: Prisma.SortOrderInput | Prisma.SortOrder
  job_listing_page_meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  company_listing_page_heading?: Prisma.SortOrder
  company_listing_page_title?: Prisma.SortOrderInput | Prisma.SortOrder
  company_listing_page_meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.page_other_itemsOrderByRelevanceInput
}

export type page_other_itemsWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.page_other_itemsWhereInput | Prisma.page_other_itemsWhereInput[]
  OR?: Prisma.page_other_itemsWhereInput[]
  NOT?: Prisma.page_other_itemsWhereInput | Prisma.page_other_itemsWhereInput[]
  login_page_heading?: Prisma.StringFilter<"page_other_items"> | string
  login_page_title?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  login_page_meta_description?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  signup_page_heading?: Prisma.StringFilter<"page_other_items"> | string
  signup_page_title?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  signup_page_meta_description?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  forget_password_page_heading?: Prisma.StringFilter<"page_other_items"> | string
  forget_password_page_title?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  forget_password_page_meta_description?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  job_listing_page_heading?: Prisma.StringFilter<"page_other_items"> | string
  job_listing_page_title?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  job_listing_page_meta_description?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  company_listing_page_heading?: Prisma.StringFilter<"page_other_items"> | string
  company_listing_page_title?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  company_listing_page_meta_description?: Prisma.StringNullableFilter<"page_other_items"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"page_other_items"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"page_other_items"> | Date | string | null
}, "id">

export type page_other_itemsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  login_page_heading?: Prisma.SortOrder
  login_page_title?: Prisma.SortOrderInput | Prisma.SortOrder
  login_page_meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  signup_page_heading?: Prisma.SortOrder
  signup_page_title?: Prisma.SortOrderInput | Prisma.SortOrder
  signup_page_meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  forget_password_page_heading?: Prisma.SortOrder
  forget_password_page_title?: Prisma.SortOrderInput | Prisma.SortOrder
  forget_password_page_meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  job_listing_page_heading?: Prisma.SortOrder
  job_listing_page_title?: Prisma.SortOrderInput | Prisma.SortOrder
  job_listing_page_meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  company_listing_page_heading?: Prisma.SortOrder
  company_listing_page_title?: Prisma.SortOrderInput | Prisma.SortOrder
  company_listing_page_meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.page_other_itemsCountOrderByAggregateInput
  _avg?: Prisma.page_other_itemsAvgOrderByAggregateInput
  _max?: Prisma.page_other_itemsMaxOrderByAggregateInput
  _min?: Prisma.page_other_itemsMinOrderByAggregateInput
  _sum?: Prisma.page_other_itemsSumOrderByAggregateInput
}

export type page_other_itemsScalarWhereWithAggregatesInput = {
  AND?: Prisma.page_other_itemsScalarWhereWithAggregatesInput | Prisma.page_other_itemsScalarWhereWithAggregatesInput[]
  OR?: Prisma.page_other_itemsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.page_other_itemsScalarWhereWithAggregatesInput | Prisma.page_other_itemsScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"page_other_items"> | bigint | number
  login_page_heading?: Prisma.StringWithAggregatesFilter<"page_other_items"> | string
  login_page_title?: Prisma.StringNullableWithAggregatesFilter<"page_other_items"> | string | null
  login_page_meta_description?: Prisma.StringNullableWithAggregatesFilter<"page_other_items"> | string | null
  signup_page_heading?: Prisma.StringWithAggregatesFilter<"page_other_items"> | string
  signup_page_title?: Prisma.StringNullableWithAggregatesFilter<"page_other_items"> | string | null
  signup_page_meta_description?: Prisma.StringNullableWithAggregatesFilter<"page_other_items"> | string | null
  forget_password_page_heading?: Prisma.StringWithAggregatesFilter<"page_other_items"> | string
  forget_password_page_title?: Prisma.StringNullableWithAggregatesFilter<"page_other_items"> | string | null
  forget_password_page_meta_description?: Prisma.StringNullableWithAggregatesFilter<"page_other_items"> | string | null
  job_listing_page_heading?: Prisma.StringWithAggregatesFilter<"page_other_items"> | string
  job_listing_page_title?: Prisma.StringNullableWithAggregatesFilter<"page_other_items"> | string | null
  job_listing_page_meta_description?: Prisma.StringNullableWithAggregatesFilter<"page_other_items"> | string | null
  company_listing_page_heading?: Prisma.StringWithAggregatesFilter<"page_other_items"> | string
  company_listing_page_title?: Prisma.StringNullableWithAggregatesFilter<"page_other_items"> | string | null
  company_listing_page_meta_description?: Prisma.StringNullableWithAggregatesFilter<"page_other_items"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"page_other_items"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"page_other_items"> | Date | string | null
}

export type page_other_itemsCreateInput = {
  id?: bigint | number
  login_page_heading: string
  login_page_title?: string | null
  login_page_meta_description?: string | null
  signup_page_heading: string
  signup_page_title?: string | null
  signup_page_meta_description?: string | null
  forget_password_page_heading: string
  forget_password_page_title?: string | null
  forget_password_page_meta_description?: string | null
  job_listing_page_heading: string
  job_listing_page_title?: string | null
  job_listing_page_meta_description?: string | null
  company_listing_page_heading: string
  company_listing_page_title?: string | null
  company_listing_page_meta_description?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type page_other_itemsUncheckedCreateInput = {
  id?: bigint | number
  login_page_heading: string
  login_page_title?: string | null
  login_page_meta_description?: string | null
  signup_page_heading: string
  signup_page_title?: string | null
  signup_page_meta_description?: string | null
  forget_password_page_heading: string
  forget_password_page_title?: string | null
  forget_password_page_meta_description?: string | null
  job_listing_page_heading: string
  job_listing_page_title?: string | null
  job_listing_page_meta_description?: string | null
  company_listing_page_heading: string
  company_listing_page_title?: string | null
  company_listing_page_meta_description?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type page_other_itemsUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  login_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  login_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  login_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signup_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  signup_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signup_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  forget_password_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  forget_password_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  forget_password_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_listing_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  job_listing_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_listing_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  company_listing_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  company_listing_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  company_listing_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type page_other_itemsUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  login_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  login_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  login_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signup_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  signup_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signup_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  forget_password_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  forget_password_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  forget_password_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_listing_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  job_listing_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_listing_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  company_listing_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  company_listing_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  company_listing_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type page_other_itemsCreateManyInput = {
  id?: bigint | number
  login_page_heading: string
  login_page_title?: string | null
  login_page_meta_description?: string | null
  signup_page_heading: string
  signup_page_title?: string | null
  signup_page_meta_description?: string | null
  forget_password_page_heading: string
  forget_password_page_title?: string | null
  forget_password_page_meta_description?: string | null
  job_listing_page_heading: string
  job_listing_page_title?: string | null
  job_listing_page_meta_description?: string | null
  company_listing_page_heading: string
  company_listing_page_title?: string | null
  company_listing_page_meta_description?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type page_other_itemsUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  login_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  login_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  login_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signup_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  signup_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signup_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  forget_password_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  forget_password_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  forget_password_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_listing_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  job_listing_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_listing_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  company_listing_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  company_listing_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  company_listing_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type page_other_itemsUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  login_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  login_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  login_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signup_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  signup_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signup_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  forget_password_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  forget_password_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  forget_password_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_listing_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  job_listing_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_listing_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  company_listing_page_heading?: Prisma.StringFieldUpdateOperationsInput | string
  company_listing_page_title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  company_listing_page_meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type page_other_itemsOrderByRelevanceInput = {
  fields: Prisma.page_other_itemsOrderByRelevanceFieldEnum | Prisma.page_other_itemsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type page_other_itemsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  login_page_heading?: Prisma.SortOrder
  login_page_title?: Prisma.SortOrder
  login_page_meta_description?: Prisma.SortOrder
  signup_page_heading?: Prisma.SortOrder
  signup_page_title?: Prisma.SortOrder
  signup_page_meta_description?: Prisma.SortOrder
  forget_password_page_heading?: Prisma.SortOrder
  forget_password_page_title?: Prisma.SortOrder
  forget_password_page_meta_description?: Prisma.SortOrder
  job_listing_page_heading?: Prisma.SortOrder
  job_listing_page_title?: Prisma.SortOrder
  job_listing_page_meta_description?: Prisma.SortOrder
  company_listing_page_heading?: Prisma.SortOrder
  company_listing_page_title?: Prisma.SortOrder
  company_listing_page_meta_description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type page_other_itemsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type page_other_itemsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  login_page_heading?: Prisma.SortOrder
  login_page_title?: Prisma.SortOrder
  login_page_meta_description?: Prisma.SortOrder
  signup_page_heading?: Prisma.SortOrder
  signup_page_title?: Prisma.SortOrder
  signup_page_meta_description?: Prisma.SortOrder
  forget_password_page_heading?: Prisma.SortOrder
  forget_password_page_title?: Prisma.SortOrder
  forget_password_page_meta_description?: Prisma.SortOrder
  job_listing_page_heading?: Prisma.SortOrder
  job_listing_page_title?: Prisma.SortOrder
  job_listing_page_meta_description?: Prisma.SortOrder
  company_listing_page_heading?: Prisma.SortOrder
  company_listing_page_title?: Prisma.SortOrder
  company_listing_page_meta_description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type page_other_itemsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  login_page_heading?: Prisma.SortOrder
  login_page_title?: Prisma.SortOrder
  login_page_meta_description?: Prisma.SortOrder
  signup_page_heading?: Prisma.SortOrder
  signup_page_title?: Prisma.SortOrder
  signup_page_meta_description?: Prisma.SortOrder
  forget_password_page_heading?: Prisma.SortOrder
  forget_password_page_title?: Prisma.SortOrder
  forget_password_page_meta_description?: Prisma.SortOrder
  job_listing_page_heading?: Prisma.SortOrder
  job_listing_page_title?: Prisma.SortOrder
  job_listing_page_meta_description?: Prisma.SortOrder
  company_listing_page_heading?: Prisma.SortOrder
  company_listing_page_title?: Prisma.SortOrder
  company_listing_page_meta_description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type page_other_itemsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type page_other_itemsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  login_page_heading?: boolean
  login_page_title?: boolean
  login_page_meta_description?: boolean
  signup_page_heading?: boolean
  signup_page_title?: boolean
  signup_page_meta_description?: boolean
  forget_password_page_heading?: boolean
  forget_password_page_title?: boolean
  forget_password_page_meta_description?: boolean
  job_listing_page_heading?: boolean
  job_listing_page_title?: boolean
  job_listing_page_meta_description?: boolean
  company_listing_page_heading?: boolean
  company_listing_page_title?: boolean
  company_listing_page_meta_description?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["page_other_items"]>



export type page_other_itemsSelectScalar = {
  id?: boolean
  login_page_heading?: boolean
  login_page_title?: boolean
  login_page_meta_description?: boolean
  signup_page_heading?: boolean
  signup_page_title?: boolean
  signup_page_meta_description?: boolean
  forget_password_page_heading?: boolean
  forget_password_page_title?: boolean
  forget_password_page_meta_description?: boolean
  job_listing_page_heading?: boolean
  job_listing_page_title?: boolean
  job_listing_page_meta_description?: boolean
  company_listing_page_heading?: boolean
  company_listing_page_title?: boolean
  company_listing_page_meta_description?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type page_other_itemsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "login_page_heading" | "login_page_title" | "login_page_meta_description" | "signup_page_heading" | "signup_page_title" | "signup_page_meta_description" | "forget_password_page_heading" | "forget_password_page_title" | "forget_password_page_meta_description" | "job_listing_page_heading" | "job_listing_page_title" | "job_listing_page_meta_description" | "company_listing_page_heading" | "company_listing_page_title" | "company_listing_page_meta_description" | "created_at" | "updated_at", ExtArgs["result"]["page_other_items"]>

export type $page_other_itemsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "page_other_items"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    login_page_heading: string
    login_page_title: string | null
    login_page_meta_description: string | null
    signup_page_heading: string
    signup_page_title: string | null
    signup_page_meta_description: string | null
    forget_password_page_heading: string
    forget_password_page_title: string | null
    forget_password_page_meta_description: string | null
    job_listing_page_heading: string
    job_listing_page_title: string | null
    job_listing_page_meta_description: string | null
    company_listing_page_heading: string
    company_listing_page_title: string | null
    company_listing_page_meta_description: string | null
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["page_other_items"]>
  composites: {}
}

export type page_other_itemsGetPayload<S extends boolean | null | undefined | page_other_itemsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$page_other_itemsPayload, S>

export type page_other_itemsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<page_other_itemsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Page_other_itemsCountAggregateInputType | true
  }

export interface page_other_itemsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['page_other_items'], meta: { name: 'page_other_items' } }
  /**
   * Find zero or one Page_other_items that matches the filter.
   * @param {page_other_itemsFindUniqueArgs} args - Arguments to find a Page_other_items
   * @example
   * // Get one Page_other_items
   * const page_other_items = await prisma.page_other_items.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends page_other_itemsFindUniqueArgs>(args: Prisma.SelectSubset<T, page_other_itemsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__page_other_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_other_itemsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Page_other_items that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {page_other_itemsFindUniqueOrThrowArgs} args - Arguments to find a Page_other_items
   * @example
   * // Get one Page_other_items
   * const page_other_items = await prisma.page_other_items.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends page_other_itemsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, page_other_itemsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__page_other_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_other_itemsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Page_other_items that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_other_itemsFindFirstArgs} args - Arguments to find a Page_other_items
   * @example
   * // Get one Page_other_items
   * const page_other_items = await prisma.page_other_items.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends page_other_itemsFindFirstArgs>(args?: Prisma.SelectSubset<T, page_other_itemsFindFirstArgs<ExtArgs>>): Prisma.Prisma__page_other_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_other_itemsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Page_other_items that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_other_itemsFindFirstOrThrowArgs} args - Arguments to find a Page_other_items
   * @example
   * // Get one Page_other_items
   * const page_other_items = await prisma.page_other_items.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends page_other_itemsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, page_other_itemsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__page_other_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_other_itemsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Page_other_items that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_other_itemsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Page_other_items
   * const page_other_items = await prisma.page_other_items.findMany()
   * 
   * // Get first 10 Page_other_items
   * const page_other_items = await prisma.page_other_items.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const page_other_itemsWithIdOnly = await prisma.page_other_items.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends page_other_itemsFindManyArgs>(args?: Prisma.SelectSubset<T, page_other_itemsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$page_other_itemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Page_other_items.
   * @param {page_other_itemsCreateArgs} args - Arguments to create a Page_other_items.
   * @example
   * // Create one Page_other_items
   * const Page_other_items = await prisma.page_other_items.create({
   *   data: {
   *     // ... data to create a Page_other_items
   *   }
   * })
   * 
   */
  create<T extends page_other_itemsCreateArgs>(args: Prisma.SelectSubset<T, page_other_itemsCreateArgs<ExtArgs>>): Prisma.Prisma__page_other_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_other_itemsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Page_other_items.
   * @param {page_other_itemsCreateManyArgs} args - Arguments to create many Page_other_items.
   * @example
   * // Create many Page_other_items
   * const page_other_items = await prisma.page_other_items.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends page_other_itemsCreateManyArgs>(args?: Prisma.SelectSubset<T, page_other_itemsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Page_other_items.
   * @param {page_other_itemsDeleteArgs} args - Arguments to delete one Page_other_items.
   * @example
   * // Delete one Page_other_items
   * const Page_other_items = await prisma.page_other_items.delete({
   *   where: {
   *     // ... filter to delete one Page_other_items
   *   }
   * })
   * 
   */
  delete<T extends page_other_itemsDeleteArgs>(args: Prisma.SelectSubset<T, page_other_itemsDeleteArgs<ExtArgs>>): Prisma.Prisma__page_other_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_other_itemsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Page_other_items.
   * @param {page_other_itemsUpdateArgs} args - Arguments to update one Page_other_items.
   * @example
   * // Update one Page_other_items
   * const page_other_items = await prisma.page_other_items.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends page_other_itemsUpdateArgs>(args: Prisma.SelectSubset<T, page_other_itemsUpdateArgs<ExtArgs>>): Prisma.Prisma__page_other_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_other_itemsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Page_other_items.
   * @param {page_other_itemsDeleteManyArgs} args - Arguments to filter Page_other_items to delete.
   * @example
   * // Delete a few Page_other_items
   * const { count } = await prisma.page_other_items.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends page_other_itemsDeleteManyArgs>(args?: Prisma.SelectSubset<T, page_other_itemsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Page_other_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_other_itemsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Page_other_items
   * const page_other_items = await prisma.page_other_items.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends page_other_itemsUpdateManyArgs>(args: Prisma.SelectSubset<T, page_other_itemsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Page_other_items.
   * @param {page_other_itemsUpsertArgs} args - Arguments to update or create a Page_other_items.
   * @example
   * // Update or create a Page_other_items
   * const page_other_items = await prisma.page_other_items.upsert({
   *   create: {
   *     // ... data to create a Page_other_items
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Page_other_items we want to update
   *   }
   * })
   */
  upsert<T extends page_other_itemsUpsertArgs>(args: Prisma.SelectSubset<T, page_other_itemsUpsertArgs<ExtArgs>>): Prisma.Prisma__page_other_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_other_itemsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Page_other_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_other_itemsCountArgs} args - Arguments to filter Page_other_items to count.
   * @example
   * // Count the number of Page_other_items
   * const count = await prisma.page_other_items.count({
   *   where: {
   *     // ... the filter for the Page_other_items we want to count
   *   }
   * })
  **/
  count<T extends page_other_itemsCountArgs>(
    args?: Prisma.Subset<T, page_other_itemsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Page_other_itemsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Page_other_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Page_other_itemsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Page_other_itemsAggregateArgs>(args: Prisma.Subset<T, Page_other_itemsAggregateArgs>): Prisma.PrismaPromise<GetPage_other_itemsAggregateType<T>>

  /**
   * Group by Page_other_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_other_itemsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends page_other_itemsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: page_other_itemsGroupByArgs['orderBy'] }
      : { orderBy?: page_other_itemsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, page_other_itemsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPage_other_itemsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the page_other_items model
 */
readonly fields: page_other_itemsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for page_other_items.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__page_other_itemsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the page_other_items model
 */
export interface page_other_itemsFieldRefs {
  readonly id: Prisma.FieldRef<"page_other_items", 'BigInt'>
  readonly login_page_heading: Prisma.FieldRef<"page_other_items", 'String'>
  readonly login_page_title: Prisma.FieldRef<"page_other_items", 'String'>
  readonly login_page_meta_description: Prisma.FieldRef<"page_other_items", 'String'>
  readonly signup_page_heading: Prisma.FieldRef<"page_other_items", 'String'>
  readonly signup_page_title: Prisma.FieldRef<"page_other_items", 'String'>
  readonly signup_page_meta_description: Prisma.FieldRef<"page_other_items", 'String'>
  readonly forget_password_page_heading: Prisma.FieldRef<"page_other_items", 'String'>
  readonly forget_password_page_title: Prisma.FieldRef<"page_other_items", 'String'>
  readonly forget_password_page_meta_description: Prisma.FieldRef<"page_other_items", 'String'>
  readonly job_listing_page_heading: Prisma.FieldRef<"page_other_items", 'String'>
  readonly job_listing_page_title: Prisma.FieldRef<"page_other_items", 'String'>
  readonly job_listing_page_meta_description: Prisma.FieldRef<"page_other_items", 'String'>
  readonly company_listing_page_heading: Prisma.FieldRef<"page_other_items", 'String'>
  readonly company_listing_page_title: Prisma.FieldRef<"page_other_items", 'String'>
  readonly company_listing_page_meta_description: Prisma.FieldRef<"page_other_items", 'String'>
  readonly created_at: Prisma.FieldRef<"page_other_items", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"page_other_items", 'DateTime'>
}
    

// Custom InputTypes
/**
 * page_other_items findUnique
 */
export type page_other_itemsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_other_items
   */
  select?: Prisma.page_other_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_other_items
   */
  omit?: Prisma.page_other_itemsOmit<ExtArgs> | null
  /**
   * Filter, which page_other_items to fetch.
   */
  where: Prisma.page_other_itemsWhereUniqueInput
}

/**
 * page_other_items findUniqueOrThrow
 */
export type page_other_itemsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_other_items
   */
  select?: Prisma.page_other_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_other_items
   */
  omit?: Prisma.page_other_itemsOmit<ExtArgs> | null
  /**
   * Filter, which page_other_items to fetch.
   */
  where: Prisma.page_other_itemsWhereUniqueInput
}

/**
 * page_other_items findFirst
 */
export type page_other_itemsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_other_items
   */
  select?: Prisma.page_other_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_other_items
   */
  omit?: Prisma.page_other_itemsOmit<ExtArgs> | null
  /**
   * Filter, which page_other_items to fetch.
   */
  where?: Prisma.page_other_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of page_other_items to fetch.
   */
  orderBy?: Prisma.page_other_itemsOrderByWithRelationInput | Prisma.page_other_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for page_other_items.
   */
  cursor?: Prisma.page_other_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` page_other_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` page_other_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of page_other_items.
   */
  distinct?: Prisma.Page_other_itemsScalarFieldEnum | Prisma.Page_other_itemsScalarFieldEnum[]
}

/**
 * page_other_items findFirstOrThrow
 */
export type page_other_itemsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_other_items
   */
  select?: Prisma.page_other_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_other_items
   */
  omit?: Prisma.page_other_itemsOmit<ExtArgs> | null
  /**
   * Filter, which page_other_items to fetch.
   */
  where?: Prisma.page_other_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of page_other_items to fetch.
   */
  orderBy?: Prisma.page_other_itemsOrderByWithRelationInput | Prisma.page_other_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for page_other_items.
   */
  cursor?: Prisma.page_other_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` page_other_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` page_other_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of page_other_items.
   */
  distinct?: Prisma.Page_other_itemsScalarFieldEnum | Prisma.Page_other_itemsScalarFieldEnum[]
}

/**
 * page_other_items findMany
 */
export type page_other_itemsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_other_items
   */
  select?: Prisma.page_other_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_other_items
   */
  omit?: Prisma.page_other_itemsOmit<ExtArgs> | null
  /**
   * Filter, which page_other_items to fetch.
   */
  where?: Prisma.page_other_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of page_other_items to fetch.
   */
  orderBy?: Prisma.page_other_itemsOrderByWithRelationInput | Prisma.page_other_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing page_other_items.
   */
  cursor?: Prisma.page_other_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` page_other_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` page_other_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of page_other_items.
   */
  distinct?: Prisma.Page_other_itemsScalarFieldEnum | Prisma.Page_other_itemsScalarFieldEnum[]
}

/**
 * page_other_items create
 */
export type page_other_itemsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_other_items
   */
  select?: Prisma.page_other_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_other_items
   */
  omit?: Prisma.page_other_itemsOmit<ExtArgs> | null
  /**
   * The data needed to create a page_other_items.
   */
  data: Prisma.XOR<Prisma.page_other_itemsCreateInput, Prisma.page_other_itemsUncheckedCreateInput>
}

/**
 * page_other_items createMany
 */
export type page_other_itemsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many page_other_items.
   */
  data: Prisma.page_other_itemsCreateManyInput | Prisma.page_other_itemsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * page_other_items update
 */
export type page_other_itemsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_other_items
   */
  select?: Prisma.page_other_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_other_items
   */
  omit?: Prisma.page_other_itemsOmit<ExtArgs> | null
  /**
   * The data needed to update a page_other_items.
   */
  data: Prisma.XOR<Prisma.page_other_itemsUpdateInput, Prisma.page_other_itemsUncheckedUpdateInput>
  /**
   * Choose, which page_other_items to update.
   */
  where: Prisma.page_other_itemsWhereUniqueInput
}

/**
 * page_other_items updateMany
 */
export type page_other_itemsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update page_other_items.
   */
  data: Prisma.XOR<Prisma.page_other_itemsUpdateManyMutationInput, Prisma.page_other_itemsUncheckedUpdateManyInput>
  /**
   * Filter which page_other_items to update
   */
  where?: Prisma.page_other_itemsWhereInput
  /**
   * Limit how many page_other_items to update.
   */
  limit?: number
}

/**
 * page_other_items upsert
 */
export type page_other_itemsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_other_items
   */
  select?: Prisma.page_other_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_other_items
   */
  omit?: Prisma.page_other_itemsOmit<ExtArgs> | null
  /**
   * The filter to search for the page_other_items to update in case it exists.
   */
  where: Prisma.page_other_itemsWhereUniqueInput
  /**
   * In case the page_other_items found by the `where` argument doesn't exist, create a new page_other_items with this data.
   */
  create: Prisma.XOR<Prisma.page_other_itemsCreateInput, Prisma.page_other_itemsUncheckedCreateInput>
  /**
   * In case the page_other_items was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.page_other_itemsUpdateInput, Prisma.page_other_itemsUncheckedUpdateInput>
}

/**
 * page_other_items delete
 */
export type page_other_itemsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_other_items
   */
  select?: Prisma.page_other_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_other_items
   */
  omit?: Prisma.page_other_itemsOmit<ExtArgs> | null
  /**
   * Filter which page_other_items to delete.
   */
  where: Prisma.page_other_itemsWhereUniqueInput
}

/**
 * page_other_items deleteMany
 */
export type page_other_itemsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which page_other_items to delete
   */
  where?: Prisma.page_other_itemsWhereInput
  /**
   * Limit how many page_other_items to delete.
   */
  limit?: number
}

/**
 * page_other_items without action
 */
export type page_other_itemsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_other_items
   */
  select?: Prisma.page_other_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_other_items
   */
  omit?: Prisma.page_other_itemsOmit<ExtArgs> | null
}
