
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `page_blog_items` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model page_blog_items
 * 
 */
export type page_blog_itemsModel = runtime.Types.Result.DefaultSelection<Prisma.$page_blog_itemsPayload>

export type AggregatePage_blog_items = {
  _count: Page_blog_itemsCountAggregateOutputType | null
  _avg: Page_blog_itemsAvgAggregateOutputType | null
  _sum: Page_blog_itemsSumAggregateOutputType | null
  _min: Page_blog_itemsMinAggregateOutputType | null
  _max: Page_blog_itemsMaxAggregateOutputType | null
}

export type Page_blog_itemsAvgAggregateOutputType = {
  id: number | null
}

export type Page_blog_itemsSumAggregateOutputType = {
  id: bigint | null
}

export type Page_blog_itemsMinAggregateOutputType = {
  id: bigint | null
  heading: string | null
  title: string | null
  meta_description: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Page_blog_itemsMaxAggregateOutputType = {
  id: bigint | null
  heading: string | null
  title: string | null
  meta_description: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Page_blog_itemsCountAggregateOutputType = {
  id: number
  heading: number
  title: number
  meta_description: number
  created_at: number
  updated_at: number
  _all: number
}


export type Page_blog_itemsAvgAggregateInputType = {
  id?: true
}

export type Page_blog_itemsSumAggregateInputType = {
  id?: true
}

export type Page_blog_itemsMinAggregateInputType = {
  id?: true
  heading?: true
  title?: true
  meta_description?: true
  created_at?: true
  updated_at?: true
}

export type Page_blog_itemsMaxAggregateInputType = {
  id?: true
  heading?: true
  title?: true
  meta_description?: true
  created_at?: true
  updated_at?: true
}

export type Page_blog_itemsCountAggregateInputType = {
  id?: true
  heading?: true
  title?: true
  meta_description?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Page_blog_itemsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which page_blog_items to aggregate.
   */
  where?: Prisma.page_blog_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of page_blog_items to fetch.
   */
  orderBy?: Prisma.page_blog_itemsOrderByWithRelationInput | Prisma.page_blog_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.page_blog_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` page_blog_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` page_blog_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned page_blog_items
  **/
  _count?: true | Page_blog_itemsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Page_blog_itemsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Page_blog_itemsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Page_blog_itemsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Page_blog_itemsMaxAggregateInputType
}

export type GetPage_blog_itemsAggregateType<T extends Page_blog_itemsAggregateArgs> = {
      [P in keyof T & keyof AggregatePage_blog_items]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePage_blog_items[P]>
    : Prisma.GetScalarType<T[P], AggregatePage_blog_items[P]>
}




export type page_blog_itemsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.page_blog_itemsWhereInput
  orderBy?: Prisma.page_blog_itemsOrderByWithAggregationInput | Prisma.page_blog_itemsOrderByWithAggregationInput[]
  by: Prisma.Page_blog_itemsScalarFieldEnum[] | Prisma.Page_blog_itemsScalarFieldEnum
  having?: Prisma.page_blog_itemsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Page_blog_itemsCountAggregateInputType | true
  _avg?: Page_blog_itemsAvgAggregateInputType
  _sum?: Page_blog_itemsSumAggregateInputType
  _min?: Page_blog_itemsMinAggregateInputType
  _max?: Page_blog_itemsMaxAggregateInputType
}

export type Page_blog_itemsGroupByOutputType = {
  id: bigint
  heading: string
  title: string | null
  meta_description: string | null
  created_at: Date | null
  updated_at: Date | null
  _count: Page_blog_itemsCountAggregateOutputType | null
  _avg: Page_blog_itemsAvgAggregateOutputType | null
  _sum: Page_blog_itemsSumAggregateOutputType | null
  _min: Page_blog_itemsMinAggregateOutputType | null
  _max: Page_blog_itemsMaxAggregateOutputType | null
}

export type GetPage_blog_itemsGroupByPayload<T extends page_blog_itemsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Page_blog_itemsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Page_blog_itemsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Page_blog_itemsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Page_blog_itemsGroupByOutputType[P]>
      }
    >
  >



export type page_blog_itemsWhereInput = {
  AND?: Prisma.page_blog_itemsWhereInput | Prisma.page_blog_itemsWhereInput[]
  OR?: Prisma.page_blog_itemsWhereInput[]
  NOT?: Prisma.page_blog_itemsWhereInput | Prisma.page_blog_itemsWhereInput[]
  id?: Prisma.BigIntFilter<"page_blog_items"> | bigint | number
  heading?: Prisma.StringFilter<"page_blog_items"> | string
  title?: Prisma.StringNullableFilter<"page_blog_items"> | string | null
  meta_description?: Prisma.StringNullableFilter<"page_blog_items"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"page_blog_items"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"page_blog_items"> | Date | string | null
}

export type page_blog_itemsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  heading?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.page_blog_itemsOrderByRelevanceInput
}

export type page_blog_itemsWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.page_blog_itemsWhereInput | Prisma.page_blog_itemsWhereInput[]
  OR?: Prisma.page_blog_itemsWhereInput[]
  NOT?: Prisma.page_blog_itemsWhereInput | Prisma.page_blog_itemsWhereInput[]
  heading?: Prisma.StringFilter<"page_blog_items"> | string
  title?: Prisma.StringNullableFilter<"page_blog_items"> | string | null
  meta_description?: Prisma.StringNullableFilter<"page_blog_items"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"page_blog_items"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"page_blog_items"> | Date | string | null
}, "id">

export type page_blog_itemsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  heading?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  meta_description?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.page_blog_itemsCountOrderByAggregateInput
  _avg?: Prisma.page_blog_itemsAvgOrderByAggregateInput
  _max?: Prisma.page_blog_itemsMaxOrderByAggregateInput
  _min?: Prisma.page_blog_itemsMinOrderByAggregateInput
  _sum?: Prisma.page_blog_itemsSumOrderByAggregateInput
}

export type page_blog_itemsScalarWhereWithAggregatesInput = {
  AND?: Prisma.page_blog_itemsScalarWhereWithAggregatesInput | Prisma.page_blog_itemsScalarWhereWithAggregatesInput[]
  OR?: Prisma.page_blog_itemsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.page_blog_itemsScalarWhereWithAggregatesInput | Prisma.page_blog_itemsScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"page_blog_items"> | bigint | number
  heading?: Prisma.StringWithAggregatesFilter<"page_blog_items"> | string
  title?: Prisma.StringNullableWithAggregatesFilter<"page_blog_items"> | string | null
  meta_description?: Prisma.StringNullableWithAggregatesFilter<"page_blog_items"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"page_blog_items"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"page_blog_items"> | Date | string | null
}

export type page_blog_itemsCreateInput = {
  id?: bigint | number
  heading: string
  title?: string | null
  meta_description?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type page_blog_itemsUncheckedCreateInput = {
  id?: bigint | number
  heading: string
  title?: string | null
  meta_description?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type page_blog_itemsUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  heading?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type page_blog_itemsUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  heading?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type page_blog_itemsCreateManyInput = {
  id?: bigint | number
  heading: string
  title?: string | null
  meta_description?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type page_blog_itemsUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  heading?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type page_blog_itemsUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  heading?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  meta_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type page_blog_itemsOrderByRelevanceInput = {
  fields: Prisma.page_blog_itemsOrderByRelevanceFieldEnum | Prisma.page_blog_itemsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type page_blog_itemsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  heading?: Prisma.SortOrder
  title?: Prisma.SortOrder
  meta_description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type page_blog_itemsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type page_blog_itemsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  heading?: Prisma.SortOrder
  title?: Prisma.SortOrder
  meta_description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type page_blog_itemsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  heading?: Prisma.SortOrder
  title?: Prisma.SortOrder
  meta_description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type page_blog_itemsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type page_blog_itemsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  heading?: boolean
  title?: boolean
  meta_description?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["page_blog_items"]>



export type page_blog_itemsSelectScalar = {
  id?: boolean
  heading?: boolean
  title?: boolean
  meta_description?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type page_blog_itemsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "heading" | "title" | "meta_description" | "created_at" | "updated_at", ExtArgs["result"]["page_blog_items"]>

export type $page_blog_itemsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "page_blog_items"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    heading: string
    title: string | null
    meta_description: string | null
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["page_blog_items"]>
  composites: {}
}

export type page_blog_itemsGetPayload<S extends boolean | null | undefined | page_blog_itemsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$page_blog_itemsPayload, S>

export type page_blog_itemsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<page_blog_itemsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Page_blog_itemsCountAggregateInputType | true
  }

export interface page_blog_itemsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['page_blog_items'], meta: { name: 'page_blog_items' } }
  /**
   * Find zero or one Page_blog_items that matches the filter.
   * @param {page_blog_itemsFindUniqueArgs} args - Arguments to find a Page_blog_items
   * @example
   * // Get one Page_blog_items
   * const page_blog_items = await prisma.page_blog_items.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends page_blog_itemsFindUniqueArgs>(args: Prisma.SelectSubset<T, page_blog_itemsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__page_blog_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_blog_itemsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Page_blog_items that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {page_blog_itemsFindUniqueOrThrowArgs} args - Arguments to find a Page_blog_items
   * @example
   * // Get one Page_blog_items
   * const page_blog_items = await prisma.page_blog_items.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends page_blog_itemsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, page_blog_itemsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__page_blog_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_blog_itemsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Page_blog_items that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_blog_itemsFindFirstArgs} args - Arguments to find a Page_blog_items
   * @example
   * // Get one Page_blog_items
   * const page_blog_items = await prisma.page_blog_items.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends page_blog_itemsFindFirstArgs>(args?: Prisma.SelectSubset<T, page_blog_itemsFindFirstArgs<ExtArgs>>): Prisma.Prisma__page_blog_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_blog_itemsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Page_blog_items that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_blog_itemsFindFirstOrThrowArgs} args - Arguments to find a Page_blog_items
   * @example
   * // Get one Page_blog_items
   * const page_blog_items = await prisma.page_blog_items.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends page_blog_itemsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, page_blog_itemsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__page_blog_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_blog_itemsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Page_blog_items that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_blog_itemsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Page_blog_items
   * const page_blog_items = await prisma.page_blog_items.findMany()
   * 
   * // Get first 10 Page_blog_items
   * const page_blog_items = await prisma.page_blog_items.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const page_blog_itemsWithIdOnly = await prisma.page_blog_items.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends page_blog_itemsFindManyArgs>(args?: Prisma.SelectSubset<T, page_blog_itemsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$page_blog_itemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Page_blog_items.
   * @param {page_blog_itemsCreateArgs} args - Arguments to create a Page_blog_items.
   * @example
   * // Create one Page_blog_items
   * const Page_blog_items = await prisma.page_blog_items.create({
   *   data: {
   *     // ... data to create a Page_blog_items
   *   }
   * })
   * 
   */
  create<T extends page_blog_itemsCreateArgs>(args: Prisma.SelectSubset<T, page_blog_itemsCreateArgs<ExtArgs>>): Prisma.Prisma__page_blog_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_blog_itemsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Page_blog_items.
   * @param {page_blog_itemsCreateManyArgs} args - Arguments to create many Page_blog_items.
   * @example
   * // Create many Page_blog_items
   * const page_blog_items = await prisma.page_blog_items.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends page_blog_itemsCreateManyArgs>(args?: Prisma.SelectSubset<T, page_blog_itemsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Page_blog_items.
   * @param {page_blog_itemsDeleteArgs} args - Arguments to delete one Page_blog_items.
   * @example
   * // Delete one Page_blog_items
   * const Page_blog_items = await prisma.page_blog_items.delete({
   *   where: {
   *     // ... filter to delete one Page_blog_items
   *   }
   * })
   * 
   */
  delete<T extends page_blog_itemsDeleteArgs>(args: Prisma.SelectSubset<T, page_blog_itemsDeleteArgs<ExtArgs>>): Prisma.Prisma__page_blog_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_blog_itemsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Page_blog_items.
   * @param {page_blog_itemsUpdateArgs} args - Arguments to update one Page_blog_items.
   * @example
   * // Update one Page_blog_items
   * const page_blog_items = await prisma.page_blog_items.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends page_blog_itemsUpdateArgs>(args: Prisma.SelectSubset<T, page_blog_itemsUpdateArgs<ExtArgs>>): Prisma.Prisma__page_blog_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_blog_itemsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Page_blog_items.
   * @param {page_blog_itemsDeleteManyArgs} args - Arguments to filter Page_blog_items to delete.
   * @example
   * // Delete a few Page_blog_items
   * const { count } = await prisma.page_blog_items.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends page_blog_itemsDeleteManyArgs>(args?: Prisma.SelectSubset<T, page_blog_itemsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Page_blog_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_blog_itemsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Page_blog_items
   * const page_blog_items = await prisma.page_blog_items.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends page_blog_itemsUpdateManyArgs>(args: Prisma.SelectSubset<T, page_blog_itemsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Page_blog_items.
   * @param {page_blog_itemsUpsertArgs} args - Arguments to update or create a Page_blog_items.
   * @example
   * // Update or create a Page_blog_items
   * const page_blog_items = await prisma.page_blog_items.upsert({
   *   create: {
   *     // ... data to create a Page_blog_items
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Page_blog_items we want to update
   *   }
   * })
   */
  upsert<T extends page_blog_itemsUpsertArgs>(args: Prisma.SelectSubset<T, page_blog_itemsUpsertArgs<ExtArgs>>): Prisma.Prisma__page_blog_itemsClient<runtime.Types.Result.GetResult<Prisma.$page_blog_itemsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Page_blog_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_blog_itemsCountArgs} args - Arguments to filter Page_blog_items to count.
   * @example
   * // Count the number of Page_blog_items
   * const count = await prisma.page_blog_items.count({
   *   where: {
   *     // ... the filter for the Page_blog_items we want to count
   *   }
   * })
  **/
  count<T extends page_blog_itemsCountArgs>(
    args?: Prisma.Subset<T, page_blog_itemsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Page_blog_itemsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Page_blog_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Page_blog_itemsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Page_blog_itemsAggregateArgs>(args: Prisma.Subset<T, Page_blog_itemsAggregateArgs>): Prisma.PrismaPromise<GetPage_blog_itemsAggregateType<T>>

  /**
   * Group by Page_blog_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {page_blog_itemsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends page_blog_itemsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: page_blog_itemsGroupByArgs['orderBy'] }
      : { orderBy?: page_blog_itemsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, page_blog_itemsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPage_blog_itemsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the page_blog_items model
 */
readonly fields: page_blog_itemsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for page_blog_items.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__page_blog_itemsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the page_blog_items model
 */
export interface page_blog_itemsFieldRefs {
  readonly id: Prisma.FieldRef<"page_blog_items", 'BigInt'>
  readonly heading: Prisma.FieldRef<"page_blog_items", 'String'>
  readonly title: Prisma.FieldRef<"page_blog_items", 'String'>
  readonly meta_description: Prisma.FieldRef<"page_blog_items", 'String'>
  readonly created_at: Prisma.FieldRef<"page_blog_items", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"page_blog_items", 'DateTime'>
}
    

// Custom InputTypes
/**
 * page_blog_items findUnique
 */
export type page_blog_itemsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_blog_items
   */
  select?: Prisma.page_blog_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_blog_items
   */
  omit?: Prisma.page_blog_itemsOmit<ExtArgs> | null
  /**
   * Filter, which page_blog_items to fetch.
   */
  where: Prisma.page_blog_itemsWhereUniqueInput
}

/**
 * page_blog_items findUniqueOrThrow
 */
export type page_blog_itemsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_blog_items
   */
  select?: Prisma.page_blog_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_blog_items
   */
  omit?: Prisma.page_blog_itemsOmit<ExtArgs> | null
  /**
   * Filter, which page_blog_items to fetch.
   */
  where: Prisma.page_blog_itemsWhereUniqueInput
}

/**
 * page_blog_items findFirst
 */
export type page_blog_itemsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_blog_items
   */
  select?: Prisma.page_blog_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_blog_items
   */
  omit?: Prisma.page_blog_itemsOmit<ExtArgs> | null
  /**
   * Filter, which page_blog_items to fetch.
   */
  where?: Prisma.page_blog_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of page_blog_items to fetch.
   */
  orderBy?: Prisma.page_blog_itemsOrderByWithRelationInput | Prisma.page_blog_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for page_blog_items.
   */
  cursor?: Prisma.page_blog_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` page_blog_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` page_blog_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of page_blog_items.
   */
  distinct?: Prisma.Page_blog_itemsScalarFieldEnum | Prisma.Page_blog_itemsScalarFieldEnum[]
}

/**
 * page_blog_items findFirstOrThrow
 */
export type page_blog_itemsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_blog_items
   */
  select?: Prisma.page_blog_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_blog_items
   */
  omit?: Prisma.page_blog_itemsOmit<ExtArgs> | null
  /**
   * Filter, which page_blog_items to fetch.
   */
  where?: Prisma.page_blog_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of page_blog_items to fetch.
   */
  orderBy?: Prisma.page_blog_itemsOrderByWithRelationInput | Prisma.page_blog_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for page_blog_items.
   */
  cursor?: Prisma.page_blog_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` page_blog_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` page_blog_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of page_blog_items.
   */
  distinct?: Prisma.Page_blog_itemsScalarFieldEnum | Prisma.Page_blog_itemsScalarFieldEnum[]
}

/**
 * page_blog_items findMany
 */
export type page_blog_itemsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_blog_items
   */
  select?: Prisma.page_blog_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_blog_items
   */
  omit?: Prisma.page_blog_itemsOmit<ExtArgs> | null
  /**
   * Filter, which page_blog_items to fetch.
   */
  where?: Prisma.page_blog_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of page_blog_items to fetch.
   */
  orderBy?: Prisma.page_blog_itemsOrderByWithRelationInput | Prisma.page_blog_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing page_blog_items.
   */
  cursor?: Prisma.page_blog_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` page_blog_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` page_blog_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of page_blog_items.
   */
  distinct?: Prisma.Page_blog_itemsScalarFieldEnum | Prisma.Page_blog_itemsScalarFieldEnum[]
}

/**
 * page_blog_items create
 */
export type page_blog_itemsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_blog_items
   */
  select?: Prisma.page_blog_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_blog_items
   */
  omit?: Prisma.page_blog_itemsOmit<ExtArgs> | null
  /**
   * The data needed to create a page_blog_items.
   */
  data: Prisma.XOR<Prisma.page_blog_itemsCreateInput, Prisma.page_blog_itemsUncheckedCreateInput>
}

/**
 * page_blog_items createMany
 */
export type page_blog_itemsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many page_blog_items.
   */
  data: Prisma.page_blog_itemsCreateManyInput | Prisma.page_blog_itemsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * page_blog_items update
 */
export type page_blog_itemsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_blog_items
   */
  select?: Prisma.page_blog_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_blog_items
   */
  omit?: Prisma.page_blog_itemsOmit<ExtArgs> | null
  /**
   * The data needed to update a page_blog_items.
   */
  data: Prisma.XOR<Prisma.page_blog_itemsUpdateInput, Prisma.page_blog_itemsUncheckedUpdateInput>
  /**
   * Choose, which page_blog_items to update.
   */
  where: Prisma.page_blog_itemsWhereUniqueInput
}

/**
 * page_blog_items updateMany
 */
export type page_blog_itemsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update page_blog_items.
   */
  data: Prisma.XOR<Prisma.page_blog_itemsUpdateManyMutationInput, Prisma.page_blog_itemsUncheckedUpdateManyInput>
  /**
   * Filter which page_blog_items to update
   */
  where?: Prisma.page_blog_itemsWhereInput
  /**
   * Limit how many page_blog_items to update.
   */
  limit?: number
}

/**
 * page_blog_items upsert
 */
export type page_blog_itemsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_blog_items
   */
  select?: Prisma.page_blog_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_blog_items
   */
  omit?: Prisma.page_blog_itemsOmit<ExtArgs> | null
  /**
   * The filter to search for the page_blog_items to update in case it exists.
   */
  where: Prisma.page_blog_itemsWhereUniqueInput
  /**
   * In case the page_blog_items found by the `where` argument doesn't exist, create a new page_blog_items with this data.
   */
  create: Prisma.XOR<Prisma.page_blog_itemsCreateInput, Prisma.page_blog_itemsUncheckedCreateInput>
  /**
   * In case the page_blog_items was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.page_blog_itemsUpdateInput, Prisma.page_blog_itemsUncheckedUpdateInput>
}

/**
 * page_blog_items delete
 */
export type page_blog_itemsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_blog_items
   */
  select?: Prisma.page_blog_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_blog_items
   */
  omit?: Prisma.page_blog_itemsOmit<ExtArgs> | null
  /**
   * Filter which page_blog_items to delete.
   */
  where: Prisma.page_blog_itemsWhereUniqueInput
}

/**
 * page_blog_items deleteMany
 */
export type page_blog_itemsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which page_blog_items to delete
   */
  where?: Prisma.page_blog_itemsWhereInput
  /**
   * Limit how many page_blog_items to delete.
   */
  limit?: number
}

/**
 * page_blog_items without action
 */
export type page_blog_itemsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the page_blog_items
   */
  select?: Prisma.page_blog_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the page_blog_items
   */
  omit?: Prisma.page_blog_itemsOmit<ExtArgs> | null
}
