
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `why_choose_items` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model why_choose_items
 * 
 */
export type why_choose_itemsModel = runtime.Types.Result.DefaultSelection<Prisma.$why_choose_itemsPayload>

export type AggregateWhy_choose_items = {
  _count: Why_choose_itemsCountAggregateOutputType | null
  _avg: Why_choose_itemsAvgAggregateOutputType | null
  _sum: Why_choose_itemsSumAggregateOutputType | null
  _min: Why_choose_itemsMinAggregateOutputType | null
  _max: Why_choose_itemsMaxAggregateOutputType | null
}

export type Why_choose_itemsAvgAggregateOutputType = {
  id: number | null
}

export type Why_choose_itemsSumAggregateOutputType = {
  id: bigint | null
}

export type Why_choose_itemsMinAggregateOutputType = {
  id: bigint | null
  icon: string | null
  heading: string | null
  text: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Why_choose_itemsMaxAggregateOutputType = {
  id: bigint | null
  icon: string | null
  heading: string | null
  text: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Why_choose_itemsCountAggregateOutputType = {
  id: number
  icon: number
  heading: number
  text: number
  created_at: number
  updated_at: number
  _all: number
}


export type Why_choose_itemsAvgAggregateInputType = {
  id?: true
}

export type Why_choose_itemsSumAggregateInputType = {
  id?: true
}

export type Why_choose_itemsMinAggregateInputType = {
  id?: true
  icon?: true
  heading?: true
  text?: true
  created_at?: true
  updated_at?: true
}

export type Why_choose_itemsMaxAggregateInputType = {
  id?: true
  icon?: true
  heading?: true
  text?: true
  created_at?: true
  updated_at?: true
}

export type Why_choose_itemsCountAggregateInputType = {
  id?: true
  icon?: true
  heading?: true
  text?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Why_choose_itemsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which why_choose_items to aggregate.
   */
  where?: Prisma.why_choose_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of why_choose_items to fetch.
   */
  orderBy?: Prisma.why_choose_itemsOrderByWithRelationInput | Prisma.why_choose_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.why_choose_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` why_choose_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` why_choose_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned why_choose_items
  **/
  _count?: true | Why_choose_itemsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Why_choose_itemsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Why_choose_itemsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Why_choose_itemsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Why_choose_itemsMaxAggregateInputType
}

export type GetWhy_choose_itemsAggregateType<T extends Why_choose_itemsAggregateArgs> = {
      [P in keyof T & keyof AggregateWhy_choose_items]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWhy_choose_items[P]>
    : Prisma.GetScalarType<T[P], AggregateWhy_choose_items[P]>
}




export type why_choose_itemsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.why_choose_itemsWhereInput
  orderBy?: Prisma.why_choose_itemsOrderByWithAggregationInput | Prisma.why_choose_itemsOrderByWithAggregationInput[]
  by: Prisma.Why_choose_itemsScalarFieldEnum[] | Prisma.Why_choose_itemsScalarFieldEnum
  having?: Prisma.why_choose_itemsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Why_choose_itemsCountAggregateInputType | true
  _avg?: Why_choose_itemsAvgAggregateInputType
  _sum?: Why_choose_itemsSumAggregateInputType
  _min?: Why_choose_itemsMinAggregateInputType
  _max?: Why_choose_itemsMaxAggregateInputType
}

export type Why_choose_itemsGroupByOutputType = {
  id: bigint
  icon: string
  heading: string
  text: string
  created_at: Date | null
  updated_at: Date | null
  _count: Why_choose_itemsCountAggregateOutputType | null
  _avg: Why_choose_itemsAvgAggregateOutputType | null
  _sum: Why_choose_itemsSumAggregateOutputType | null
  _min: Why_choose_itemsMinAggregateOutputType | null
  _max: Why_choose_itemsMaxAggregateOutputType | null
}

export type GetWhy_choose_itemsGroupByPayload<T extends why_choose_itemsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Why_choose_itemsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Why_choose_itemsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Why_choose_itemsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Why_choose_itemsGroupByOutputType[P]>
      }
    >
  >



export type why_choose_itemsWhereInput = {
  AND?: Prisma.why_choose_itemsWhereInput | Prisma.why_choose_itemsWhereInput[]
  OR?: Prisma.why_choose_itemsWhereInput[]
  NOT?: Prisma.why_choose_itemsWhereInput | Prisma.why_choose_itemsWhereInput[]
  id?: Prisma.BigIntFilter<"why_choose_items"> | bigint | number
  icon?: Prisma.StringFilter<"why_choose_items"> | string
  heading?: Prisma.StringFilter<"why_choose_items"> | string
  text?: Prisma.StringFilter<"why_choose_items"> | string
  created_at?: Prisma.DateTimeNullableFilter<"why_choose_items"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"why_choose_items"> | Date | string | null
}

export type why_choose_itemsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  heading?: Prisma.SortOrder
  text?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.why_choose_itemsOrderByRelevanceInput
}

export type why_choose_itemsWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.why_choose_itemsWhereInput | Prisma.why_choose_itemsWhereInput[]
  OR?: Prisma.why_choose_itemsWhereInput[]
  NOT?: Prisma.why_choose_itemsWhereInput | Prisma.why_choose_itemsWhereInput[]
  icon?: Prisma.StringFilter<"why_choose_items"> | string
  heading?: Prisma.StringFilter<"why_choose_items"> | string
  text?: Prisma.StringFilter<"why_choose_items"> | string
  created_at?: Prisma.DateTimeNullableFilter<"why_choose_items"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"why_choose_items"> | Date | string | null
}, "id">

export type why_choose_itemsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  heading?: Prisma.SortOrder
  text?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.why_choose_itemsCountOrderByAggregateInput
  _avg?: Prisma.why_choose_itemsAvgOrderByAggregateInput
  _max?: Prisma.why_choose_itemsMaxOrderByAggregateInput
  _min?: Prisma.why_choose_itemsMinOrderByAggregateInput
  _sum?: Prisma.why_choose_itemsSumOrderByAggregateInput
}

export type why_choose_itemsScalarWhereWithAggregatesInput = {
  AND?: Prisma.why_choose_itemsScalarWhereWithAggregatesInput | Prisma.why_choose_itemsScalarWhereWithAggregatesInput[]
  OR?: Prisma.why_choose_itemsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.why_choose_itemsScalarWhereWithAggregatesInput | Prisma.why_choose_itemsScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"why_choose_items"> | bigint | number
  icon?: Prisma.StringWithAggregatesFilter<"why_choose_items"> | string
  heading?: Prisma.StringWithAggregatesFilter<"why_choose_items"> | string
  text?: Prisma.StringWithAggregatesFilter<"why_choose_items"> | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"why_choose_items"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"why_choose_items"> | Date | string | null
}

export type why_choose_itemsCreateInput = {
  id?: bigint | number
  icon: string
  heading: string
  text: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type why_choose_itemsUncheckedCreateInput = {
  id?: bigint | number
  icon: string
  heading: string
  text: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type why_choose_itemsUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  heading?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type why_choose_itemsUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  heading?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type why_choose_itemsCreateManyInput = {
  id?: bigint | number
  icon: string
  heading: string
  text: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type why_choose_itemsUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  heading?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type why_choose_itemsUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  heading?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type why_choose_itemsOrderByRelevanceInput = {
  fields: Prisma.why_choose_itemsOrderByRelevanceFieldEnum | Prisma.why_choose_itemsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type why_choose_itemsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  heading?: Prisma.SortOrder
  text?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type why_choose_itemsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type why_choose_itemsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  heading?: Prisma.SortOrder
  text?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type why_choose_itemsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  heading?: Prisma.SortOrder
  text?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type why_choose_itemsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type why_choose_itemsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  icon?: boolean
  heading?: boolean
  text?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["why_choose_items"]>



export type why_choose_itemsSelectScalar = {
  id?: boolean
  icon?: boolean
  heading?: boolean
  text?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type why_choose_itemsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "icon" | "heading" | "text" | "created_at" | "updated_at", ExtArgs["result"]["why_choose_items"]>

export type $why_choose_itemsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "why_choose_items"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    icon: string
    heading: string
    text: string
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["why_choose_items"]>
  composites: {}
}

export type why_choose_itemsGetPayload<S extends boolean | null | undefined | why_choose_itemsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$why_choose_itemsPayload, S>

export type why_choose_itemsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<why_choose_itemsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Why_choose_itemsCountAggregateInputType | true
  }

export interface why_choose_itemsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['why_choose_items'], meta: { name: 'why_choose_items' } }
  /**
   * Find zero or one Why_choose_items that matches the filter.
   * @param {why_choose_itemsFindUniqueArgs} args - Arguments to find a Why_choose_items
   * @example
   * // Get one Why_choose_items
   * const why_choose_items = await prisma.why_choose_items.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends why_choose_itemsFindUniqueArgs>(args: Prisma.SelectSubset<T, why_choose_itemsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__why_choose_itemsClient<runtime.Types.Result.GetResult<Prisma.$why_choose_itemsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Why_choose_items that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {why_choose_itemsFindUniqueOrThrowArgs} args - Arguments to find a Why_choose_items
   * @example
   * // Get one Why_choose_items
   * const why_choose_items = await prisma.why_choose_items.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends why_choose_itemsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, why_choose_itemsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__why_choose_itemsClient<runtime.Types.Result.GetResult<Prisma.$why_choose_itemsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Why_choose_items that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {why_choose_itemsFindFirstArgs} args - Arguments to find a Why_choose_items
   * @example
   * // Get one Why_choose_items
   * const why_choose_items = await prisma.why_choose_items.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends why_choose_itemsFindFirstArgs>(args?: Prisma.SelectSubset<T, why_choose_itemsFindFirstArgs<ExtArgs>>): Prisma.Prisma__why_choose_itemsClient<runtime.Types.Result.GetResult<Prisma.$why_choose_itemsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Why_choose_items that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {why_choose_itemsFindFirstOrThrowArgs} args - Arguments to find a Why_choose_items
   * @example
   * // Get one Why_choose_items
   * const why_choose_items = await prisma.why_choose_items.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends why_choose_itemsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, why_choose_itemsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__why_choose_itemsClient<runtime.Types.Result.GetResult<Prisma.$why_choose_itemsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Why_choose_items that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {why_choose_itemsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Why_choose_items
   * const why_choose_items = await prisma.why_choose_items.findMany()
   * 
   * // Get first 10 Why_choose_items
   * const why_choose_items = await prisma.why_choose_items.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const why_choose_itemsWithIdOnly = await prisma.why_choose_items.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends why_choose_itemsFindManyArgs>(args?: Prisma.SelectSubset<T, why_choose_itemsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$why_choose_itemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Why_choose_items.
   * @param {why_choose_itemsCreateArgs} args - Arguments to create a Why_choose_items.
   * @example
   * // Create one Why_choose_items
   * const Why_choose_items = await prisma.why_choose_items.create({
   *   data: {
   *     // ... data to create a Why_choose_items
   *   }
   * })
   * 
   */
  create<T extends why_choose_itemsCreateArgs>(args: Prisma.SelectSubset<T, why_choose_itemsCreateArgs<ExtArgs>>): Prisma.Prisma__why_choose_itemsClient<runtime.Types.Result.GetResult<Prisma.$why_choose_itemsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Why_choose_items.
   * @param {why_choose_itemsCreateManyArgs} args - Arguments to create many Why_choose_items.
   * @example
   * // Create many Why_choose_items
   * const why_choose_items = await prisma.why_choose_items.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends why_choose_itemsCreateManyArgs>(args?: Prisma.SelectSubset<T, why_choose_itemsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Why_choose_items.
   * @param {why_choose_itemsDeleteArgs} args - Arguments to delete one Why_choose_items.
   * @example
   * // Delete one Why_choose_items
   * const Why_choose_items = await prisma.why_choose_items.delete({
   *   where: {
   *     // ... filter to delete one Why_choose_items
   *   }
   * })
   * 
   */
  delete<T extends why_choose_itemsDeleteArgs>(args: Prisma.SelectSubset<T, why_choose_itemsDeleteArgs<ExtArgs>>): Prisma.Prisma__why_choose_itemsClient<runtime.Types.Result.GetResult<Prisma.$why_choose_itemsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Why_choose_items.
   * @param {why_choose_itemsUpdateArgs} args - Arguments to update one Why_choose_items.
   * @example
   * // Update one Why_choose_items
   * const why_choose_items = await prisma.why_choose_items.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends why_choose_itemsUpdateArgs>(args: Prisma.SelectSubset<T, why_choose_itemsUpdateArgs<ExtArgs>>): Prisma.Prisma__why_choose_itemsClient<runtime.Types.Result.GetResult<Prisma.$why_choose_itemsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Why_choose_items.
   * @param {why_choose_itemsDeleteManyArgs} args - Arguments to filter Why_choose_items to delete.
   * @example
   * // Delete a few Why_choose_items
   * const { count } = await prisma.why_choose_items.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends why_choose_itemsDeleteManyArgs>(args?: Prisma.SelectSubset<T, why_choose_itemsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Why_choose_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {why_choose_itemsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Why_choose_items
   * const why_choose_items = await prisma.why_choose_items.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends why_choose_itemsUpdateManyArgs>(args: Prisma.SelectSubset<T, why_choose_itemsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Why_choose_items.
   * @param {why_choose_itemsUpsertArgs} args - Arguments to update or create a Why_choose_items.
   * @example
   * // Update or create a Why_choose_items
   * const why_choose_items = await prisma.why_choose_items.upsert({
   *   create: {
   *     // ... data to create a Why_choose_items
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Why_choose_items we want to update
   *   }
   * })
   */
  upsert<T extends why_choose_itemsUpsertArgs>(args: Prisma.SelectSubset<T, why_choose_itemsUpsertArgs<ExtArgs>>): Prisma.Prisma__why_choose_itemsClient<runtime.Types.Result.GetResult<Prisma.$why_choose_itemsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Why_choose_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {why_choose_itemsCountArgs} args - Arguments to filter Why_choose_items to count.
   * @example
   * // Count the number of Why_choose_items
   * const count = await prisma.why_choose_items.count({
   *   where: {
   *     // ... the filter for the Why_choose_items we want to count
   *   }
   * })
  **/
  count<T extends why_choose_itemsCountArgs>(
    args?: Prisma.Subset<T, why_choose_itemsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Why_choose_itemsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Why_choose_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Why_choose_itemsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Why_choose_itemsAggregateArgs>(args: Prisma.Subset<T, Why_choose_itemsAggregateArgs>): Prisma.PrismaPromise<GetWhy_choose_itemsAggregateType<T>>

  /**
   * Group by Why_choose_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {why_choose_itemsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends why_choose_itemsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: why_choose_itemsGroupByArgs['orderBy'] }
      : { orderBy?: why_choose_itemsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, why_choose_itemsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWhy_choose_itemsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the why_choose_items model
 */
readonly fields: why_choose_itemsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for why_choose_items.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__why_choose_itemsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the why_choose_items model
 */
export interface why_choose_itemsFieldRefs {
  readonly id: Prisma.FieldRef<"why_choose_items", 'BigInt'>
  readonly icon: Prisma.FieldRef<"why_choose_items", 'String'>
  readonly heading: Prisma.FieldRef<"why_choose_items", 'String'>
  readonly text: Prisma.FieldRef<"why_choose_items", 'String'>
  readonly created_at: Prisma.FieldRef<"why_choose_items", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"why_choose_items", 'DateTime'>
}
    

// Custom InputTypes
/**
 * why_choose_items findUnique
 */
export type why_choose_itemsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the why_choose_items
   */
  select?: Prisma.why_choose_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the why_choose_items
   */
  omit?: Prisma.why_choose_itemsOmit<ExtArgs> | null
  /**
   * Filter, which why_choose_items to fetch.
   */
  where: Prisma.why_choose_itemsWhereUniqueInput
}

/**
 * why_choose_items findUniqueOrThrow
 */
export type why_choose_itemsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the why_choose_items
   */
  select?: Prisma.why_choose_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the why_choose_items
   */
  omit?: Prisma.why_choose_itemsOmit<ExtArgs> | null
  /**
   * Filter, which why_choose_items to fetch.
   */
  where: Prisma.why_choose_itemsWhereUniqueInput
}

/**
 * why_choose_items findFirst
 */
export type why_choose_itemsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the why_choose_items
   */
  select?: Prisma.why_choose_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the why_choose_items
   */
  omit?: Prisma.why_choose_itemsOmit<ExtArgs> | null
  /**
   * Filter, which why_choose_items to fetch.
   */
  where?: Prisma.why_choose_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of why_choose_items to fetch.
   */
  orderBy?: Prisma.why_choose_itemsOrderByWithRelationInput | Prisma.why_choose_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for why_choose_items.
   */
  cursor?: Prisma.why_choose_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` why_choose_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` why_choose_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of why_choose_items.
   */
  distinct?: Prisma.Why_choose_itemsScalarFieldEnum | Prisma.Why_choose_itemsScalarFieldEnum[]
}

/**
 * why_choose_items findFirstOrThrow
 */
export type why_choose_itemsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the why_choose_items
   */
  select?: Prisma.why_choose_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the why_choose_items
   */
  omit?: Prisma.why_choose_itemsOmit<ExtArgs> | null
  /**
   * Filter, which why_choose_items to fetch.
   */
  where?: Prisma.why_choose_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of why_choose_items to fetch.
   */
  orderBy?: Prisma.why_choose_itemsOrderByWithRelationInput | Prisma.why_choose_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for why_choose_items.
   */
  cursor?: Prisma.why_choose_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` why_choose_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` why_choose_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of why_choose_items.
   */
  distinct?: Prisma.Why_choose_itemsScalarFieldEnum | Prisma.Why_choose_itemsScalarFieldEnum[]
}

/**
 * why_choose_items findMany
 */
export type why_choose_itemsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the why_choose_items
   */
  select?: Prisma.why_choose_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the why_choose_items
   */
  omit?: Prisma.why_choose_itemsOmit<ExtArgs> | null
  /**
   * Filter, which why_choose_items to fetch.
   */
  where?: Prisma.why_choose_itemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of why_choose_items to fetch.
   */
  orderBy?: Prisma.why_choose_itemsOrderByWithRelationInput | Prisma.why_choose_itemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing why_choose_items.
   */
  cursor?: Prisma.why_choose_itemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` why_choose_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` why_choose_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of why_choose_items.
   */
  distinct?: Prisma.Why_choose_itemsScalarFieldEnum | Prisma.Why_choose_itemsScalarFieldEnum[]
}

/**
 * why_choose_items create
 */
export type why_choose_itemsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the why_choose_items
   */
  select?: Prisma.why_choose_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the why_choose_items
   */
  omit?: Prisma.why_choose_itemsOmit<ExtArgs> | null
  /**
   * The data needed to create a why_choose_items.
   */
  data: Prisma.XOR<Prisma.why_choose_itemsCreateInput, Prisma.why_choose_itemsUncheckedCreateInput>
}

/**
 * why_choose_items createMany
 */
export type why_choose_itemsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many why_choose_items.
   */
  data: Prisma.why_choose_itemsCreateManyInput | Prisma.why_choose_itemsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * why_choose_items update
 */
export type why_choose_itemsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the why_choose_items
   */
  select?: Prisma.why_choose_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the why_choose_items
   */
  omit?: Prisma.why_choose_itemsOmit<ExtArgs> | null
  /**
   * The data needed to update a why_choose_items.
   */
  data: Prisma.XOR<Prisma.why_choose_itemsUpdateInput, Prisma.why_choose_itemsUncheckedUpdateInput>
  /**
   * Choose, which why_choose_items to update.
   */
  where: Prisma.why_choose_itemsWhereUniqueInput
}

/**
 * why_choose_items updateMany
 */
export type why_choose_itemsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update why_choose_items.
   */
  data: Prisma.XOR<Prisma.why_choose_itemsUpdateManyMutationInput, Prisma.why_choose_itemsUncheckedUpdateManyInput>
  /**
   * Filter which why_choose_items to update
   */
  where?: Prisma.why_choose_itemsWhereInput
  /**
   * Limit how many why_choose_items to update.
   */
  limit?: number
}

/**
 * why_choose_items upsert
 */
export type why_choose_itemsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the why_choose_items
   */
  select?: Prisma.why_choose_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the why_choose_items
   */
  omit?: Prisma.why_choose_itemsOmit<ExtArgs> | null
  /**
   * The filter to search for the why_choose_items to update in case it exists.
   */
  where: Prisma.why_choose_itemsWhereUniqueInput
  /**
   * In case the why_choose_items found by the `where` argument doesn't exist, create a new why_choose_items with this data.
   */
  create: Prisma.XOR<Prisma.why_choose_itemsCreateInput, Prisma.why_choose_itemsUncheckedCreateInput>
  /**
   * In case the why_choose_items was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.why_choose_itemsUpdateInput, Prisma.why_choose_itemsUncheckedUpdateInput>
}

/**
 * why_choose_items delete
 */
export type why_choose_itemsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the why_choose_items
   */
  select?: Prisma.why_choose_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the why_choose_items
   */
  omit?: Prisma.why_choose_itemsOmit<ExtArgs> | null
  /**
   * Filter which why_choose_items to delete.
   */
  where: Prisma.why_choose_itemsWhereUniqueInput
}

/**
 * why_choose_items deleteMany
 */
export type why_choose_itemsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which why_choose_items to delete
   */
  where?: Prisma.why_choose_itemsWhereInput
  /**
   * Limit how many why_choose_items to delete.
   */
  limit?: number
}

/**
 * why_choose_items without action
 */
export type why_choose_itemsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the why_choose_items
   */
  select?: Prisma.why_choose_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the why_choose_items
   */
  omit?: Prisma.why_choose_itemsOmit<ExtArgs> | null
}
